<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleNewPublishNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage</code>
 */
class CircleContentMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 文本描述
     *
     * Generated from protobuf field <code>string Text = 1;</code>
     */
    private $Text = '';
    /**
     * 图片列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Images = 2;</code>
     */
    private $Images;
    /**
     * 链接、分享
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Link = 3;</code>
     */
    private $Link = null;
    /**
     * 视频
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Video = 4;</code>
     */
    private $Video = null;
    /**
     * Generated from protobuf field <code>string Ext = 5;</code>
     */
    protected $Ext = '';
    /**
     * Generated from protobuf field <code>int32 Type = 6;</code>
     */
    protected $Type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Text
     *           文本描述
     *     @type \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage[]|\Google\Protobuf\Internal\RepeatedField $Images
     *           图片列表
     *     @type \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage $Link
     *           链接、分享
     *     @type \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage $Video
     *           视频
     *     @type string $Ext
     *     @type int $Type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CircleNewPublishNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 文本描述
     *
     * Generated from protobuf field <code>string Text = 1;</code>
     * @return string
     */
    public function getText()
    {
        return $this->Text;
    }

    /**
     * 文本描述
     *
     * Generated from protobuf field <code>string Text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->Text = $var;

        return $this;
    }

    /**
     * 图片列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Images = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImages()
    {
        return $this->Images;
    }

    /**
     * 图片列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Images = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage::class);
        $this->Images = $arr;

        return $this;
    }

    /**
     * 链接、分享
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Link = 3;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage
     */
    public function getLink()
    {
        return $this->Link;
    }

    /**
     * 链接、分享
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Link = 3;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage_CircleContentMessage_CircleNewsContentMessage::class);
        $this->Link = $var;

        return $this;
    }

    /**
     * 视频
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Video = 4;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage
     */
    public function getVideo()
    {
        return $this->Video;
    }

    /**
     * 视频
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage Video = 4;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage_CircleContentMessage_CircleNewsContentMessage::class);
        $this->Video = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Ext = 5;</code>
     * @return string
     */
    public function getExt()
    {
        return $this->Ext;
    }

    /**
     * Generated from protobuf field <code>string Ext = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->Ext = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CircleContentMessage::class, \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage_CircleContentMessage::class);

