<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.PoiMessage</code>
 */
class PoiMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 城市
     *
     * Generated from protobuf field <code>string City = 1;</code>
     */
    private $City = '';
    /**
     * 显示名称，如：万达广场
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     * 详细地址
     *
     * Generated from protobuf field <code>string Address = 3;</code>
     */
    private $Address = '';
    /**
     * 纬度
     *
     * Generated from protobuf field <code>float Lat = 4;</code>
     */
    private $Lat = 0.0;
    /**
     * 经度
     *
     * Generated from protobuf field <code>float Lng = 5;</code>
     */
    private $Lng = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $City
     *           城市
     *     @type string $Name
     *           显示名称，如：万达广场
     *     @type string $Address
     *           详细地址
     *     @type float $Lat
     *           纬度
     *     @type float $Lng
     *           经度
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PostSNSNewsTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string City = 1;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string City = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     * 显示名称，如：万达广场
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 显示名称，如：万达广场
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 详细地址
     *
     * Generated from protobuf field <code>string Address = 3;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * 详细地址
     *
     * Generated from protobuf field <code>string Address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

    /**
     * 纬度
     *
     * Generated from protobuf field <code>float Lat = 4;</code>
     * @return float
     */
    public function getLat()
    {
        return $this->Lat;
    }

    /**
     * 纬度
     *
     * Generated from protobuf field <code>float Lat = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->Lat = $var;

        return $this;
    }

    /**
     * 经度
     *
     * Generated from protobuf field <code>float Lng = 5;</code>
     * @return float
     */
    public function getLng()
    {
        return $this->Lng;
    }

    /**
     * 经度
     *
     * Generated from protobuf field <code>float Lng = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLng($var)
    {
        GPBUtil::checkFloat($var);
        $this->Lng = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PoiMessage::class, \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage_PoiMessage::class);

