<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddFriendWithSceneTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.AddFriendWithSceneTaskMessage</code>
 */
class AddFriendWithSceneTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 要添加的手机号码,微信号（后期支持v1 stranger？）
     *
     * Generated from protobuf field <code>string Friend = 2;</code>
     */
    private $Friend = '';
    /**
     * 发送的验证消息
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     */
    private $Message = '';
    /**
     * 添加场景（0 搜索，1 通过群聊(无效）， 2 通讯录， 3 名片（未测试）, 4 附近的人（未测试））
     *
     * Generated from protobuf field <code>int32 Scene = 4;</code>
     */
    private $Scene = 0;
    /**
     *备注名
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     */
    private $Remark = '';
    /**
     *任务Id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;
    /**
     * 标签
     *
     * Generated from protobuf field <code>string Label = 7;</code>
     */
    protected $Label = '';
    /**
     *朋友圈权限：缺省0，不看她 1 不让她看 2 仅聊天 8
     *
     * Generated from protobuf field <code>int32 Permission = 11;</code>
     */
    protected $Permission = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $Friend
     *           要添加的手机号码,微信号（后期支持v1 stranger？）
     *     @type string $Message
     *           发送的验证消息
     *     @type int $Scene
     *           添加场景（0 搜索，1 通过群聊(无效）， 2 通讯录， 3 名片（未测试）, 4 附近的人（未测试））
     *     @type string $Remark
     *          备注名
     *     @type int|string $TaskId
     *          任务Id
     *     @type string $Label
     *           标签
     *     @type int $Permission
     *          朋友圈权限：缺省0，不看她 1 不让她看 2 仅聊天 8
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AddFriendWithSceneTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 要添加的手机号码,微信号（后期支持v1 stranger？）
     *
     * Generated from protobuf field <code>string Friend = 2;</code>
     * @return string
     */
    public function getFriend()
    {
        return $this->Friend;
    }

    /**
     * 要添加的手机号码,微信号（后期支持v1 stranger？）
     *
     * Generated from protobuf field <code>string Friend = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriend($var)
    {
        GPBUtil::checkString($var, True);
        $this->Friend = $var;

        return $this;
    }

    /**
     * 发送的验证消息
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * 发送的验证消息
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * 添加场景（0 搜索，1 通过群聊(无效）， 2 通讯录， 3 名片（未测试）, 4 附近的人（未测试））
     *
     * Generated from protobuf field <code>int32 Scene = 4;</code>
     * @return int
     */
    public function getScene()
    {
        return $this->Scene;
    }

    /**
     * 添加场景（0 搜索，1 通过群聊(无效）， 2 通讯录， 3 名片（未测试）, 4 附近的人（未测试））
     *
     * Generated from protobuf field <code>int32 Scene = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkInt32($var);
        $this->Scene = $var;

        return $this;
    }

    /**
     *备注名
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     *备注名
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 标签
     *
     * Generated from protobuf field <code>string Label = 7;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->Label;
    }

    /**
     * 标签
     *
     * Generated from protobuf field <code>string Label = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Label = $var;

        return $this;
    }

    /**
     *朋友圈权限：缺省0，不看她 1 不让她看 2 仅聊天 8
     *
     * Generated from protobuf field <code>int32 Permission = 11;</code>
     * @return int
     */
    public function getPermission()
    {
        return $this->Permission;
    }

    /**
     *朋友圈权限：缺省0，不看她 1 不让她看 2 仅聊天 8
     *
     * Generated from protobuf field <code>int32 Permission = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPermission($var)
    {
        GPBUtil::checkInt32($var);
        $this->Permission = $var;

        return $this;
    }

}

