<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgreeJoinChatRoomTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.AgreeJoinChatRoomTaskMessage</code>
 */
class AgreeJoinChatRoomTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Talker = 2;</code>
     */
    private $Talker = '';
    /**
     * 邀请消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     */
    private $MsgSvrId = 0;
    /**
     * 回传邀请信息的内容（json）
     *
     * Generated from protobuf field <code>string MsgContent = 4;</code>
     */
    private $MsgContent = '';
    /**
     * Generated from protobuf field <code>int64 taskId = 5;</code>
     */
    private $taskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type string $Talker
     *           邀请者
     *     @type int|string $MsgSvrId
     *           邀请消息的msgSvrId
     *     @type string $MsgContent
     *           回传邀请信息的内容（json）
     *     @type int|string $taskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AgreeJoinChatRoomTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Talker = 2;</code>
     * @return string
     */
    public function getTalker()
    {
        return $this->Talker;
    }

    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Talker = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTalker($var)
    {
        GPBUtil::checkString($var, True);
        $this->Talker = $var;

        return $this;
    }

    /**
     * 邀请消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     * 邀请消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     * 回传邀请信息的内容（json）
     *
     * Generated from protobuf field <code>string MsgContent = 4;</code>
     * @return string
     */
    public function getMsgContent()
    {
        return $this->MsgContent;
    }

    /**
     * 回传邀请信息的内容（json）
     *
     * Generated from protobuf field <code>string MsgContent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->MsgContent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 taskId = 5;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->taskId;
    }

    /**
     * Generated from protobuf field <code>int64 taskId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->taskId = $var;

        return $this;
    }

}

