<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BizContactPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.BizContactMessage</code>
 */
class BizContactMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * id
     *
     * Generated from protobuf field <code>string Username = 1;</code>
     */
    private $Username = '';
    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     */
    private $Alias = '';
    /**
     * 昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     */
    private $Nickname = '';
    /**
     *头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     */
    private $Avatar = '';
    /**
     * 公众号图标
     *
     * Generated from protobuf field <code>string Icon = 5;</code>
     */
    private $Icon = '';
    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 6;</code>
     */
    private $Desc = '';
    /**
     * 注册公司
     *
     * Generated from protobuf field <code>string Company = 7;</code>
     */
    private $Company = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Username
     *           id
     *     @type string $Alias
     *           微信号
     *     @type string $Nickname
     *           昵称
     *     @type string $Avatar
     *          头像 
     *     @type string $Icon
     *           公众号图标
     *     @type string $Desc
     *           描述
     *     @type string $Company
     *           注册公司
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BizContactPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * id
     *
     * Generated from protobuf field <code>string Username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->Username;
    }

    /**
     * id
     *
     * Generated from protobuf field <code>string Username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->Username = $var;

        return $this;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->Alias;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->Alias = $var;

        return $this;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->Nickname;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->Nickname = $var;

        return $this;
    }

    /**
     *头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     *头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * 公众号图标
     *
     * Generated from protobuf field <code>string Icon = 5;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * 公众号图标
     *
     * Generated from protobuf field <code>string Icon = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->Icon = $var;

        return $this;
    }

    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 6;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->Desc;
    }

    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->Desc = $var;

        return $this;
    }

    /**
     * 注册公司
     *
     * Generated from protobuf field <code>string Company = 7;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->Company;
    }

    /**
     * 注册公司
     *
     * Generated from protobuf field <code>string Company = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->Company = $var;

        return $this;
    }

}

