<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CDNDownloadResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.CDNDownloadResultNoticeMessage</code>
 */
class CDNDownloadResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 2;</code>
     */
    private $Success = false;
    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     */
    private $ErrMsg = '';
    /**
     * 任务请求的文件id
     *
     * Generated from protobuf field <code>string FileId = 4;</code>
     */
    private $FileId = '';
    /**
     * 任务请求的msgsvrid
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 5;</code>
     */
    private $MsgSvrId = 0;
    /**
     *
     *
     * Generated from protobuf field <code>string Url = 6;</code>
     */
    private $Url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type bool $Success
     *           是否成功
     *     @type string $ErrMsg
     *           错误内容描述 Success = true 忽略
     *     @type string $FileId
     *           任务请求的文件id
     *     @type int|string $MsgSvrId
     *           任务请求的msgsvrid
     *     @type string $Url
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CDNDownloadResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 2;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

    /**
     * 任务请求的文件id
     *
     * Generated from protobuf field <code>string FileId = 4;</code>
     * @return string
     */
    public function getFileId()
    {
        return $this->FileId;
    }

    /**
     * 任务请求的文件id
     *
     * Generated from protobuf field <code>string FileId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileId = $var;

        return $this;
    }

    /**
     * 任务请求的msgsvrid
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 5;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     * 任务请求的msgsvrid
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Url = 6;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->Url;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->Url = $var;

        return $this;
    }

}

