<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomChangedNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ChatRoomChangedNoticeMessage</code>
 */
class ChatRoomChangedNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>string UserName = 2;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumChatRoomChange What = 3;</code>
     */
    private $What = 0;
    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     */
    private $Content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $UserName
     *     @type int $What
     *     @type string $Content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChatRoomChangedNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserName = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumChatRoomChange What = 3;</code>
     * @return int
     */
    public function getWhat()
    {
        return $this->What;
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumChatRoomChange What = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWhat($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumChatRoomChange::class);
        $this->What = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

}

