<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomAddNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ChatRoomAddNoticeMessage</code>
 */
class ChatRoomAddNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.ChatRoomMessage ChatRoom = 2;</code>
     */
    private $ChatRoom = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type \Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage $ChatRoom
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChatRoomAddNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.ChatRoomMessage ChatRoom = 2;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage
     */
    public function getChatRoom()
    {
        return $this->ChatRoom;
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.ChatRoomMessage ChatRoom = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage $var
     * @return $this
     */
    public function setChatRoom($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage::class);
        $this->ChatRoom = $var;

        return $this;
    }

}

