<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleNewPublishNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

if (false) {
    /**
     * This class is deprecated. Use Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage instead.
     * @deprecated
     */
    class CircleInformationMessage_CircleContentMessage_CircleNewsContentMessage {}
}
class_exists(CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage::class);
@trigger_error('Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage_CircleContentMessage_CircleNewsContentMessage is deprecated and will be removed in the next major release. Use Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage\CircleNewsContentMessage instead', E_USER_DEPRECATED);

