<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleCommentDeleteTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.CircleCommentDeleteTaskResultNoticeMessage</code>
 */
class CircleCommentDeleteTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     */
    private $Success = false;
    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    private $Code = 0;
    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     */
    private $ErrMsg = '';
    /**
     * 朋友圈去id
     *
     * Generated from protobuf field <code>int64 CircleId = 4;</code>
     */
    private $CircleId = 0;
    /**
     * 评论id
     *
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     */
    private $CommentId = 0;
    /**
     * jkt 本地存储的主键id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 7;</code>
     */
    private $WeChatId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Success
     *           是否成功
     *     @type int $Code
     *           错误码 Success = true 忽略
     *     @type string $ErrMsg
     *           错误内容描述 Success = true 忽略
     *     @type int|string $CircleId
     *           朋友圈去id
     *     @type int|string $CommentId
     *           评论id
     *     @type int|string $TaskId
     *           jkt 本地存储的主键id
     *     @type string $WeChatId
     *           商家所属微信号
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CircleCommentDeleteTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumErrorCode::class);
        $this->Code = $var;

        return $this;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

    /**
     * 朋友圈去id
     *
     * Generated from protobuf field <code>int64 CircleId = 4;</code>
     * @return int|string
     */
    public function getCircleId()
    {
        return $this->CircleId;
    }

    /**
     * 朋友圈去id
     *
     * Generated from protobuf field <code>int64 CircleId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCircleId($var)
    {
        GPBUtil::checkInt64($var);
        $this->CircleId = $var;

        return $this;
    }

    /**
     * 评论id
     *
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     * @return int|string
     */
    public function getCommentId()
    {
        return $this->CommentId;
    }

    /**
     * 评论id
     *
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommentId($var)
    {
        GPBUtil::checkInt64($var);
        $this->CommentId = $var;

        return $this;
    }

    /**
     * jkt 本地存储的主键id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * jkt 本地存储的主键id
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 7;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

}

