<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleMsgPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.CircleMsgPushNoticeMessage</code>
 */
class CircleMsgPushNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleCommentMessage Comments = 2;</code>
     */
    private $Comments;
    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleLikeMessage Likes = 3;</code>
     */
    private $Likes;
    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type \Jubo\JuLiao\IM\Wx\Proto\CircleCommentMessage[]|\Google\Protobuf\Internal\RepeatedField $Comments
     *          
     *     @type \Jubo\JuLiao\IM\Wx\Proto\CircleLikeMessage[]|\Google\Protobuf\Internal\RepeatedField $Likes
     *          
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CircleMsgPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleCommentMessage Comments = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getComments()
    {
        return $this->Comments;
    }

    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleCommentMessage Comments = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\CircleCommentMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setComments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\CircleCommentMessage::class);
        $this->Comments = $arr;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleLikeMessage Likes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLikes()
    {
        return $this->Likes;
    }

    /**
     *
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.CircleLikeMessage Likes = 3;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\CircleLikeMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLikes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\CircleLikeMessage::class);
        $this->Likes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

