<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactLabelTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ContactLabelTaskMessage</code>
 */
class ContactLabelTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 标签名 id!=0 会设置为该标签名
     *
     * Generated from protobuf field <code>string LabelName = 2;</code>
     */
    private $LabelName = '';
    /**
     * 标签id，0则新建标签（如存在同名标签则会失败）
     *
     * Generated from protobuf field <code>int32 LabelId = 3;</code>
     */
    private $LabelId = 0;
    /**
     * 新增的wxid，用,分隔
     *
     * Generated from protobuf field <code>string AddList = 4;</code>
     */
    private $AddList = '';
    /**
     * 删除的wxid，用,分隔
     *
     * Generated from protobuf field <code>string DelList = 5;</code>
     */
    private $DelList = '';
    /**
     * Generated from protobuf field <code>int64 taskId = 6;</code>
     */
    private $taskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $LabelName
     *           标签名 id!=0 会设置为该标签名
     *     @type int $LabelId
     *           标签id，0则新建标签（如存在同名标签则会失败）
     *     @type string $AddList
     *           新增的wxid，用,分隔
     *     @type string $DelList
     *           删除的wxid，用,分隔
     *     @type int|string $taskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ContactLabelTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 标签名 id!=0 会设置为该标签名
     *
     * Generated from protobuf field <code>string LabelName = 2;</code>
     * @return string
     */
    public function getLabelName()
    {
        return $this->LabelName;
    }

    /**
     * 标签名 id!=0 会设置为该标签名
     *
     * Generated from protobuf field <code>string LabelName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LabelName = $var;

        return $this;
    }

    /**
     * 标签id，0则新建标签（如存在同名标签则会失败）
     *
     * Generated from protobuf field <code>int32 LabelId = 3;</code>
     * @return int
     */
    public function getLabelId()
    {
        return $this->LabelId;
    }

    /**
     * 标签id，0则新建标签（如存在同名标签则会失败）
     *
     * Generated from protobuf field <code>int32 LabelId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLabelId($var)
    {
        GPBUtil::checkInt32($var);
        $this->LabelId = $var;

        return $this;
    }

    /**
     * 新增的wxid，用,分隔
     *
     * Generated from protobuf field <code>string AddList = 4;</code>
     * @return string
     */
    public function getAddList()
    {
        return $this->AddList;
    }

    /**
     * 新增的wxid，用,分隔
     *
     * Generated from protobuf field <code>string AddList = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddList($var)
    {
        GPBUtil::checkString($var, True);
        $this->AddList = $var;

        return $this;
    }

    /**
     * 删除的wxid，用,分隔
     *
     * Generated from protobuf field <code>string DelList = 5;</code>
     * @return string
     */
    public function getDelList()
    {
        return $this->DelList;
    }

    /**
     * 删除的wxid，用,分隔
     *
     * Generated from protobuf field <code>string DelList = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDelList($var)
    {
        GPBUtil::checkString($var, True);
        $this->DelList = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 taskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->taskId;
    }

    /**
     * Generated from protobuf field <code>int64 taskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->taskId = $var;

        return $this;
    }

}

