<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactInfoNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ContactInfoNoticeMessage</code>
 */
class ContactInfoNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 联系人信息
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.StrangerMessage Contact = 2;</code>
     */
    private $Contact = null;
    /**
     * Generated from protobuf field <code>int64 TaskId = 3;</code>
     */
    private $TaskId = 0;
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 4;</code>
     */
    private $Success = false;
    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 5;</code>
     */
    private $ErrMsg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type \Jubo\JuLiao\IM\Wx\Proto\StrangerMessage $Contact
     *           联系人信息
     *     @type int|string $TaskId
     *     @type bool $Success
     *           是否成功
     *     @type string $ErrMsg
     *           错误内容描述 Success = true 忽略
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ContactInfoNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 联系人信息
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.StrangerMessage Contact = 2;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\StrangerMessage
     */
    public function getContact()
    {
        return $this->Contact;
    }

    /**
     * 联系人信息
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.StrangerMessage Contact = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\StrangerMessage $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\StrangerMessage::class);
        $this->Contact = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 3;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 4;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 5;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

}

