<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhoneActionTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.EnumPhoneAction</code>
 */
class EnumPhoneAction
{
    /**
     * 空
     *
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * 重启手机
     *
     * Generated from protobuf enum <code>Reboot = 1;</code>
     */
    const Reboot = 1;
    /**
     * 上传日志
     *
     * Generated from protobuf enum <code>UploadLog = 2;</code>
     */
    const UploadLog = 2;
    /**
     * 上传本地文件
     *
     * Generated from protobuf enum <code>UploadFile = 3;</code>
     */
    const UploadFile = 3;
    /**
     * 清除客服系统的图片缓存
     *
     * Generated from protobuf enum <code>CleanAppCache = 4;</code>
     */
    const CleanAppCache = 4;
    /**
     * 清除微信的图片视频缓存
     *
     * Generated from protobuf enum <code>CleanWxCache = 5;</code>
     */
    const CleanWxCache = 5;
    /**
     * 清除手机缓存的文件url（用于防止重复上传）
     *
     * Generated from protobuf enum <code>CleanFileUrlCache = 6;</code>
     */
    const CleanFileUrlCache = 6;
    /**
     * 拨打电话
     *
     * Generated from protobuf enum <code>PhoneCall = 7;</code>
     */
    const PhoneCall = 7;
    /**
     * 重启微信
     *
     * Generated from protobuf enum <code>RestartWx = 9;</code>
     */
    const RestartWx = 9;
    /**
     * 退出客服系统
     *
     * Generated from protobuf enum <code>RestartSelf = 10;</code>
     */
    const RestartSelf = 10;

    private static $valueToName = [
        self::None => 'None',
        self::Reboot => 'Reboot',
        self::UploadLog => 'UploadLog',
        self::UploadFile => 'UploadFile',
        self::CleanAppCache => 'CleanAppCache',
        self::CleanWxCache => 'CleanWxCache',
        self::CleanFileUrlCache => 'CleanFileUrlCache',
        self::PhoneCall => 'PhoneCall',
        self::RestartWx => 'RestartWx',
        self::RestartSelf => 'RestartSelf',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

