<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransportMessage.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use UnexpectedValueException;

/**
 * 聊天内容类型
 *
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.EnumContentType</code>
 */
class EnumContentType
{
    /**
     * 未知内容
     *
     * Generated from protobuf enum <code>UnknownContent = 0;</code>
     */
    const UnknownContent = 0;
    /**
     * 文本内容
     *
     * Generated from protobuf enum <code>Text = 1;</code>
     */
    const Text = 1;
    /**
     * 图片消息
     *
     * Generated from protobuf enum <code>Picture = 2;</code>
     */
    const Picture = 2;
    /**
     * 语音消息
     *
     * Generated from protobuf enum <code>Voice = 3;</code>
     */
    const Voice = 3;
    /**
     * 视频消息
     *
     * Generated from protobuf enum <code>Video = 4;</code>
     */
    const Video = 4;
    /**
     *系统消息
     *
     * Generated from protobuf enum <code>System = 5;</code>
     */
    const System = 5;
    /**
     * 链接消息
     *
     * Generated from protobuf enum <code>Link = 6;</code>
     */
    const Link = 6;
    /**
     * 扩展的链接消息（小程序分享等），内容为xml格式，暂未使用
     *
     * Generated from protobuf enum <code>LinkExt = 7;</code>
     */
    const LinkExt = 7;
    /**
     * 文件发送
     *
     * Generated from protobuf enum <code>File = 8;</code>
     */
    const File = 8;
    /**
     * 名片
     *
     * Generated from protobuf enum <code>NameCard = 9;</code>
     */
    const NameCard = 9;
    /**
     * 位置信息
     *
     * Generated from protobuf enum <code>Location = 10;</code>
     */
    const Location = 10;
    /**
     * 红包
     *
     * Generated from protobuf enum <code>LuckyMoney = 11;</code>
     */
    const LuckyMoney = 11;
    /**
     * 转账
     *
     * Generated from protobuf enum <code>MoneyTrans = 12;</code>
     */
    const MoneyTrans = 12;
    /**
     * 小程序
     *
     * Generated from protobuf enum <code>WeApp = 13;</code>
     */
    const WeApp = 13;
    /**
     *
     *
     * Generated from protobuf enum <code>Emoji = 14;</code>
     */
    const Emoji = 14;
    /**
     * 群管理消息
     *
     * Generated from protobuf enum <code>RoomManage = 15;</code>
     */
    const RoomManage = 15;
    /**
     * 领取红包消息
     *
     * Generated from protobuf enum <code>Sys_LuckyMoney = 16;</code>
     */
    const Sys_LuckyMoney = 16;
    /**
     * 群聊系统消息
     *
     * Generated from protobuf enum <code>RoomSystem = 17;</code>
     */
    const RoomSystem = 17;
    /**
     * 公众号文章
     *
     * Generated from protobuf enum <code>BizLink = 18;</code>
     */
    const BizLink = 18;
    /**
     * 语音通话
     *
     * Generated from protobuf enum <code>AudioCall = 19;</code>
     */
    const AudioCall = 19;
    /**
     * 视频通话
     *
     * Generated from protobuf enum <code>VideoCall = 20;</code>
     */
    const VideoCall = 20;
    /**
     * 服务通知
     *
     * Generated from protobuf enum <code>NotifyMsg = 21;</code>
     */
    const NotifyMsg = 21;
    /**
     * 引用通知
     *
     * Generated from protobuf enum <code>QuoteMsg = 22;</code>
     */
    const QuoteMsg = 22;
    /**
     *接龙
     *
     * Generated from protobuf enum <code>JieLongMsg = 23;</code>
     */
    const JieLongMsg = 23;
    /**
     * 视频号消息
     *
     * Generated from protobuf enum <code>ShiPinHao = 24;</code>
     */
    const ShiPinHao = 24;
    /**
     * 群直播消息
     *
     * Generated from protobuf enum <code>RoomLiving = 25;</code>
     */
    const RoomLiving = 25;
    /**
     * 拍一拍
     *
     * Generated from protobuf enum <code>PaiYiPai = 26;</code>
     */
    const PaiYiPai = 26;
    /**
     *Music = 27; // 分享音乐
     *
     * Generated from protobuf enum <code>FinderLive = 28;</code>
     */
    const FinderLive = 28;
    /**
     *客服号名片
     *
     * Generated from protobuf enum <code>KefuNameCard = 29;</code>
     */
    const KefuNameCard = 29;
    /**
     *企业微信名片
     *
     * Generated from protobuf enum <code>QiyeNameCard = 30;</code>
     */
    const QiyeNameCard = 30;
    /**
     * 不支持的消息
     *
     * Generated from protobuf enum <code>UnSupport = 99;</code>
     */
    const UnSupport = 99;

    private static $valueToName = [
        self::UnknownContent => 'UnknownContent',
        self::Text => 'Text',
        self::Picture => 'Picture',
        self::Voice => 'Voice',
        self::Video => 'Video',
        self::System => 'System',
        self::Link => 'Link',
        self::LinkExt => 'LinkExt',
        self::File => 'File',
        self::NameCard => 'NameCard',
        self::Location => 'Location',
        self::LuckyMoney => 'LuckyMoney',
        self::MoneyTrans => 'MoneyTrans',
        self::WeApp => 'WeApp',
        self::Emoji => 'Emoji',
        self::RoomManage => 'RoomManage',
        self::Sys_LuckyMoney => 'Sys_LuckyMoney',
        self::RoomSystem => 'RoomSystem',
        self::BizLink => 'BizLink',
        self::AudioCall => 'AudioCall',
        self::VideoCall => 'VideoCall',
        self::NotifyMsg => 'NotifyMsg',
        self::QuoteMsg => 'QuoteMsg',
        self::JieLongMsg => 'JieLongMsg',
        self::ShiPinHao => 'ShiPinHao',
        self::RoomLiving => 'RoomLiving',
        self::PaiYiPai => 'PaiYiPai',
        self::FinderLive => 'FinderLive',
        self::KefuNameCard => 'KefuNameCard',
        self::QiyeNameCard => 'QiyeNameCard',
        self::UnSupport => 'UnSupport',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

