<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransportMessage.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use UnexpectedValueException;

/**
 *被强制下线的原因
 *
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.EnumForceOfflineReason</code>
 */
class EnumForceOfflineReason
{
    /**
     *就是要下线你 
     *
     * Generated from protobuf enum <code>NoReason = 0;</code>
     */
    const NoReason = 0;
    /**
     *别处登录挤下线了 
     *
     * Generated from protobuf enum <code>FuckedByOtherAuthorizer = 1;</code>
     */
    const FuckedByOtherAuthorizer = 1;
    /**
     * 被重新分配
     *
     * Generated from protobuf enum <code>ByReAlloc = 2;</code>
     */
    const ByReAlloc = 2;
    /**
     * 设备下线而下线
     *
     * Generated from protobuf enum <code>ByDeviceOffline = 3;</code>
     */
    const ByDeviceOffline = 3;
    /**
     * 微信主动下线
     *
     * Generated from protobuf enum <code>ByWeChatOffline = 4;</code>
     */
    const ByWeChatOffline = 4;

    private static $valueToName = [
        self::NoReason => 'NoReason',
        self::FuckedByOtherAuthorizer => 'FuckedByOtherAuthorizer',
        self::ByReAlloc => 'ByReAlloc',
        self::ByDeviceOffline => 'ByDeviceOffline',
        self::ByWeChatOffline => 'ByWeChatOffline',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

