<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomChangedNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.EnumChatRoomChange</code>
 */
class EnumChatRoomChange
{
    /**
     * 群成员
     *
     * Generated from protobuf enum <code>Change_MemberList = 0;</code>
     */
    const Change_MemberList = 0;
    /**
     * 公告
     *
     * Generated from protobuf enum <code>Change_PublicNotice = 1;</code>
     */
    const Change_PublicNotice = 1;
    /**
     * 群昵称
     *
     * Generated from protobuf enum <code>Change_NickName = 2;</code>
     */
    const Change_NickName = 2;
    /**
     * 群显示名，内容格式：[username:showname,]
     *
     * Generated from protobuf enum <code>Change_ShowName = 3;</code>
     */
    const Change_ShowName = 3;
    /**
     * 自己的群显示名
     *
     * Generated from protobuf enum <code>Change_MyShowName = 4;</code>
     */
    const Change_MyShowName = 4;
    /**
     * 群主
     *
     * Generated from protobuf enum <code>Change_Owner = 5;</code>
     */
    const Change_Owner = 5;
    /**
     * 群聊头像
     *
     * Generated from protobuf enum <code>Change_Avatar = 6;</code>
     */
    const Change_Avatar = 6;
    /**
     * 群成员新增
     *
     * Generated from protobuf enum <code>Change_MemberAdd = 7;</code>
     */
    const Change_MemberAdd = 7;
    /**
     * 群成员减少
     *
     * Generated from protobuf enum <code>Change_MemberDel = 8;</code>
     */
    const Change_MemberDel = 8;

    private static $valueToName = [
        self::Change_MemberList => 'Change_MemberList',
        self::Change_PublicNotice => 'Change_PublicNotice',
        self::Change_NickName => 'Change_NickName',
        self::Change_ShowName => 'Change_ShowName',
        self::Change_MyShowName => 'Change_MyShowName',
        self::Change_Owner => 'Change_Owner',
        self::Change_Avatar => 'Change_Avatar',
        self::Change_MemberAdd => 'Change_MemberAdd',
        self::Change_MemberDel => 'Change_MemberDel',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

