<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransportMessage.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use UnexpectedValueException;

/**
 * 全局错误码表
 *
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode</code>
 */
class EnumErrorCode
{
    /**
     *无错误
     *
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     *无权限
     *
     * Generated from protobuf enum <code>NoRight = 1001;</code>
     */
    const NoRight = 1001;
    /**
     *数据信息不合法
     *
     * Generated from protobuf enum <code>InvalidParam = 1002;</code>
     */
    const InvalidParam = 1002;
    /**
     *内部处理错误
     *
     * Generated from protobuf enum <code>InternalError = 1003;</code>
     */
    const InternalError = 1003;
    /**
     *发送消息或指令时对方不在线
     *
     * Generated from protobuf enum <code>TargetNotOnline = 1004;</code>
     */
    const TargetNotOnline = 1004;

    private static $valueToName = [
        self::Success => 'Success',
        self::NoRight => 'NoRight',
        self::InvalidParam => 'InvalidParam',
        self::InternalError => 'InternalError',
        self::TargetNotOnline => 'TargetNotOnline',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

