<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessageByContentTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ForwardMessageByContentTaskMessage</code>
 */
class ForwardMessageByContentTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *目标人群id列表，用分号;分隔
     *
     * Generated from protobuf field <code>string FriendIds = 2;</code>
     */
    private $FriendIds = '';
    /**
     * 消息Id,
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     */
    private $MsgSvrId = 0;
    /**
     * 消息的原始类型，一般为49，链接消息. 42 公众号名片
     *
     * Generated from protobuf field <code>int32 MsgType = 4;</code>
     */
    private $MsgType = 0;
    /**
     * 消息的原始内容
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     */
    private $Content = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;
    /**
     * 消息缩略图url
     *
     * Generated from protobuf field <code>string Thumb = 7;</code>
     */
    private $Thumb = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type string $FriendIds
     *          目标人群id列表，用分号;分隔
     *     @type int|string $MsgSvrId
     *           消息Id,
     *     @type int $MsgType
     *           消息的原始类型，一般为49，链接消息. 42 公众号名片
     *     @type string $Content
     *           消息的原始内容
     *     @type int|string $TaskId
     *          
     *     @type string $Thumb
     *           消息缩略图url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ForwardMessageByContentTask::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *目标人群id列表，用分号;分隔
     *
     * Generated from protobuf field <code>string FriendIds = 2;</code>
     * @return string
     */
    public function getFriendIds()
    {
        return $this->FriendIds;
    }

    /**
     *目标人群id列表，用分号;分隔
     *
     * Generated from protobuf field <code>string FriendIds = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendIds = $var;

        return $this;
    }

    /**
     * 消息Id,
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     * 消息Id,
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     * 消息的原始类型，一般为49，链接消息. 42 公众号名片
     *
     * Generated from protobuf field <code>int32 MsgType = 4;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->MsgType;
    }

    /**
     * 消息的原始类型，一般为49，链接消息. 42 公众号名片
     *
     * Generated from protobuf field <code>int32 MsgType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkInt32($var);
        $this->MsgType = $var;

        return $this;
    }

    /**
     * 消息的原始内容
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 消息的原始内容
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 消息缩略图url
     *
     * Generated from protobuf field <code>string Thumb = 7;</code>
     * @return string
     */
    public function getThumb()
    {
        return $this->Thumb;
    }

    /**
     * 消息缩略图url
     *
     * Generated from protobuf field <code>string Thumb = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setThumb($var)
    {
        GPBUtil::checkString($var, True);
        $this->Thumb = $var;

        return $this;
    }

}

