<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendAddReqeustNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.FriendAddReqeustNoticeMessage</code>
 */
class FriendAddReqeustNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 请求好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     * 微信号
     *
     * Generated from protobuf field <code>string FriendNo = 3;</code>
     */
    private $FriendNo = '';
    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string FriendNick = 4;</code>
     */
    private $FriendNick = '';
    /**
     * 招呼语
     *
     * Generated from protobuf field <code>string Reason = 5;</code>
     */
    private $Reason = '';
    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 6;</code>
     */
    private $Avatar = '';
    /**
     * 来源 (17: 名片分享）
     *
     * Generated from protobuf field <code>int32 Source = 7;</code>
     */
    private $Source = 0;
    /**
     * 来源的微信id（推荐人，群聊房间号）
     *
     * Generated from protobuf field <code>string SourceUser = 8;</code>
     */
    private $SourceUser = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 9;</code>
     */
    private $Gender = 0;
    /**
     *省份 (国家用不上）
     *
     * Generated from protobuf field <code>string Province = 10;</code>
     */
    private $Province = '';
    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 11;</code>
     */
    private $City = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type string $FriendId
     *           请求好友微信内部全局唯一识别码
     *     @type string $FriendNo
     *           微信号
     *     @type string $FriendNick
     *           好友的微信昵称
     *     @type string $Reason
     *           招呼语
     *     @type string $Avatar
     *          微信头像 
     *     @type int $Source
     *           来源 (17: 名片分享）
     *     @type string $SourceUser
     *           来源的微信id（推荐人，群聊房间号）
     *     @type int $Gender
     *          性别
     *     @type string $Province
     *          省份 (国家用不上）
     *     @type string $City
     *          城市
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FriendAddReqeustNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 请求好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 请求好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string FriendNo = 3;</code>
     * @return string
     */
    public function getFriendNo()
    {
        return $this->FriendNo;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string FriendNo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendNo = $var;

        return $this;
    }

    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string FriendNick = 4;</code>
     * @return string
     */
    public function getFriendNick()
    {
        return $this->FriendNick;
    }

    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string FriendNick = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendNick($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendNick = $var;

        return $this;
    }

    /**
     * 招呼语
     *
     * Generated from protobuf field <code>string Reason = 5;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->Reason;
    }

    /**
     * 招呼语
     *
     * Generated from protobuf field <code>string Reason = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->Reason = $var;

        return $this;
    }

    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 6;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * 来源 (17: 名片分享）
     *
     * Generated from protobuf field <code>int32 Source = 7;</code>
     * @return int
     */
    public function getSource()
    {
        return $this->Source;
    }

    /**
     * 来源 (17: 名片分享）
     *
     * Generated from protobuf field <code>int32 Source = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->Source = $var;

        return $this;
    }

    /**
     * 来源的微信id（推荐人，群聊房间号）
     *
     * Generated from protobuf field <code>string SourceUser = 8;</code>
     * @return string
     */
    public function getSourceUser()
    {
        return $this->SourceUser;
    }

    /**
     * 来源的微信id（推荐人，群聊房间号）
     *
     * Generated from protobuf field <code>string SourceUser = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceUser = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 9;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->Gender;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumGender::class);
        $this->Gender = $var;

        return $this;
    }

    /**
     *省份 (国家用不上）
     *
     * Generated from protobuf field <code>string Province = 10;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->Province;
    }

    /**
     *省份 (国家用不上）
     *
     * Generated from protobuf field <code>string Province = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->Province = $var;

        return $this;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 11;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

}

