<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendTalkNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.FriendTalkNoticeMessage</code>
 */
class FriendTalkNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     */
    private $FriendId = '';
    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    private $ContentType = 0;
    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     */
    private $Content = '';
    /**
     *服务端的主键id
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     */
    private $MsgId = 0;
    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     */
    private $msgSvrId = 0;
    /**
     * 扩展信息，图片视频{"length":10000, "hdlen":20000, "duration":30} 文件大小，原图大小，视频时长
     *
     * Generated from protobuf field <code>string Ext = 9;</code>
     */
    private $Ext = '';
    /**
     * 消息时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 10;</code>
     */
    private $CreateTime = 0;
    /**
     * 发送者昵称
     *
     * Generated from protobuf field <code>string NickName = 11;</code>
     */
    private $NickName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type string $FriendId
     *           好友微信内部全局唯一识别码
     *     @type int $ContentType
     *           发送的消息内容类型
     *     @type string $Content
     *           内容 二进制流
     *     @type int|string $MsgId
     *          服务端的主键id
     *     @type int|string $msgSvrId
     *           消息唯一id
     *     @type string $Ext
     *           扩展信息，图片视频{"length":10000, "hdlen":20000, "duration":30} 文件大小，原图大小，视频时长
     *     @type int|string $CreateTime
     *           消息时间
     *     @type string $NickName
     *           发送者昵称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FriendTalkNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 好友微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumContentType::class);
        $this->ContentType = $var;

        return $this;
    }

    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     *服务端的主键id
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     *服务端的主键id
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->msgSvrId;
    }

    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgSvrId = $var;

        return $this;
    }

    /**
     * 扩展信息，图片视频{"length":10000, "hdlen":20000, "duration":30} 文件大小，原图大小，视频时长
     *
     * Generated from protobuf field <code>string Ext = 9;</code>
     * @return string
     */
    public function getExt()
    {
        return $this->Ext;
    }

    /**
     * 扩展信息，图片视频{"length":10000, "hdlen":20000, "duration":30} 文件大小，原图大小，视频时长
     *
     * Generated from protobuf field <code>string Ext = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->Ext = $var;

        return $this;
    }

    /**
     * 消息时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 10;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     * 消息时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     * 发送者昵称
     *
     * Generated from protobuf field <code>string NickName = 11;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * 发送者昵称
     *
     * Generated from protobuf field <code>string NickName = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

}

