<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendDetectResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.FriendDetectResultNoticeMessage</code>
 */
class FriendDetectResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     */
    private $TaskId = 0;
    /**
     * 任务开始时间
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     */
    private $StartTime = 0;
    /**
     * 任务结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     */
    private $EndTime = 0;
    /**
     *是否清粉完毕
     *
     * Generated from protobuf field <code>bool IsFinished = 5;</code>
     */
    private $IsFinished = false;
    /**
     * 已检测人数
     *
     * Generated from protobuf field <code>int32 Count = 6;</code>
     */
    private $Count = 0;
    /**
     * 跳过检测人数：设置时间内检测过，聊天过，朋友圈互动过
     *
     * Generated from protobuf field <code>int32 SkipCount = 7;</code>
     */
    private $SkipCount = 0;
    /**
     * 已删除的人数
     *
     * Generated from protobuf field <code>int32 DelCount = 8;</code>
     */
    private $DelCount = 0;
    /**
     * 僵尸粉id
     *
     * Generated from protobuf field <code>repeated string Zombies = 9;</code>
     */
    private $Zombies;
    /**
     * 拉黑的僵尸粉
     *
     * Generated from protobuf field <code>repeated string BlockedList = 10;</code>
     */
    private $BlockedList;
    /**
     * 账号异常（被封号）
     *
     * Generated from protobuf field <code>repeated string BannedList = 11;</code>
     */
    private $BannedList;
    /**
     * 账号已注销
     *
     * Generated from protobuf field <code>repeated string CanceledList = 12;</code>
     */
    private $CanceledList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type int|string $TaskId
     *           所执行的任务ID
     *     @type int|string $StartTime
     *           任务开始时间
     *     @type int|string $EndTime
     *           任务结束时间
     *     @type bool $IsFinished
     *          是否清粉完毕
     *     @type int $Count
     *           已检测人数
     *     @type int $SkipCount
     *           跳过检测人数：设置时间内检测过，聊天过，朋友圈互动过
     *     @type int $DelCount
     *           已删除的人数
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Zombies
     *           僵尸粉id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $BlockedList
     *           拉黑的僵尸粉
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $BannedList
     *           账号异常（被封号）
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $CanceledList
     *           账号已注销
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FriendDetectResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 任务开始时间
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 任务开始时间
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 任务结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 任务结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     *是否清粉完毕
     *
     * Generated from protobuf field <code>bool IsFinished = 5;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return $this->IsFinished;
    }

    /**
     *是否清粉完毕
     *
     * Generated from protobuf field <code>bool IsFinished = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * 已检测人数
     *
     * Generated from protobuf field <code>int32 Count = 6;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * 已检测人数
     *
     * Generated from protobuf field <code>int32 Count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * 跳过检测人数：设置时间内检测过，聊天过，朋友圈互动过
     *
     * Generated from protobuf field <code>int32 SkipCount = 7;</code>
     * @return int
     */
    public function getSkipCount()
    {
        return $this->SkipCount;
    }

    /**
     * 跳过检测人数：设置时间内检测过，聊天过，朋友圈互动过
     *
     * Generated from protobuf field <code>int32 SkipCount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSkipCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->SkipCount = $var;

        return $this;
    }

    /**
     * 已删除的人数
     *
     * Generated from protobuf field <code>int32 DelCount = 8;</code>
     * @return int
     */
    public function getDelCount()
    {
        return $this->DelCount;
    }

    /**
     * 已删除的人数
     *
     * Generated from protobuf field <code>int32 DelCount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setDelCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->DelCount = $var;

        return $this;
    }

    /**
     * 僵尸粉id
     *
     * Generated from protobuf field <code>repeated string Zombies = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getZombies()
    {
        return $this->Zombies;
    }

    /**
     * 僵尸粉id
     *
     * Generated from protobuf field <code>repeated string Zombies = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setZombies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Zombies = $arr;

        return $this;
    }

    /**
     * 拉黑的僵尸粉
     *
     * Generated from protobuf field <code>repeated string BlockedList = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockedList()
    {
        return $this->BlockedList;
    }

    /**
     * 拉黑的僵尸粉
     *
     * Generated from protobuf field <code>repeated string BlockedList = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockedList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->BlockedList = $arr;

        return $this;
    }

    /**
     * 账号异常（被封号）
     *
     * Generated from protobuf field <code>repeated string BannedList = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBannedList()
    {
        return $this->BannedList;
    }

    /**
     * 账号异常（被封号）
     *
     * Generated from protobuf field <code>repeated string BannedList = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBannedList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->BannedList = $arr;

        return $this;
    }

    /**
     * 账号已注销
     *
     * Generated from protobuf field <code>repeated string CanceledList = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCanceledList()
    {
        return $this->CanceledList;
    }

    /**
     * 账号已注销
     *
     * Generated from protobuf field <code>repeated string CanceledList = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCanceledList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->CanceledList = $arr;

        return $this;
    }

}

