<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetA8KeyTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.GetA8KeyTaskMessage</code>
 */
class GetA8KeyTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 类型，0：辅助验证 1：公众号文章
     *
     * Generated from protobuf field <code>int32 Type = 2;</code>
     */
    private $Type = 0;
    /**
     *
     *
     * Generated from protobuf field <code>string Url = 3;</code>
     */
    private $Url = '';
    /**
     * 消息发送者UserName,微信团队：weixin，公众号文章：公众号id
     *
     * Generated from protobuf field <code>string UserName = 4;</code>
     */
    private $UserName = '';
    /**
     * 消息id，暂时不用
     *
     * Generated from protobuf field <code>string MsgSvrId = 5;</code>
     */
    private $MsgSvrId = '';
    /**
     *备用
     *
     * Generated from protobuf field <code>int32 Reason = 6;</code>
     */
    private $Reason = 0;
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type int $Type
     *           类型，0：辅助验证 1：公众号文章
     *     @type string $Url
     *          
     *     @type string $UserName
     *           消息发送者UserName,微信团队：weixin，公众号文章：公众号id
     *     @type string $MsgSvrId
     *           消息id，暂时不用
     *     @type int $Reason
     *          备用
     *     @type int|string $TaskId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetA8KeyTask::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 类型，0：辅助验证 1：公众号文章
     *
     * Generated from protobuf field <code>int32 Type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * 类型，0：辅助验证 1：公众号文章
     *
     * Generated from protobuf field <code>int32 Type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Url = 3;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->Url;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->Url = $var;

        return $this;
    }

    /**
     * 消息发送者UserName,微信团队：weixin，公众号文章：公众号id
     *
     * Generated from protobuf field <code>string UserName = 4;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * 消息发送者UserName,微信团队：weixin，公众号文章：公众号id
     *
     * Generated from protobuf field <code>string UserName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * 消息id，暂时不用
     *
     * Generated from protobuf field <code>string MsgSvrId = 5;</code>
     * @return string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     * 消息id，暂时不用
     *
     * Generated from protobuf field <code>string MsgSvrId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     *备用
     *
     * Generated from protobuf field <code>int32 Reason = 6;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->Reason;
    }

    /**
     *备用
     *
     * Generated from protobuf field <code>int32 Reason = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkInt32($var);
        $this->Reason = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

