<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPoiListTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.GetPoiListTaskMessage</code>
 */
class GetPoiListTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    protected $WeChatId = '';
    /**
     * Generated from protobuf field <code>double Lat = 2;</code>
     */
    protected $Lat = 0.0;
    /**
     * Generated from protobuf field <code>double Lng = 3;</code>
     */
    protected $Lng = 0.0;
    /**
     *搜索地址的关键字，可以不传经纬度，只传关键字
     *
     * Generated from protobuf field <code>string Keyword = 4;</code>
     */
    protected $Keyword = '';
    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     */
    protected $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type float $Lat
     *     @type float $Lng
     *     @type string $Keyword
     *          搜索地址的关键字，可以不传经纬度，只传关键字
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetPoiListTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Lat = 2;</code>
     * @return float
     */
    public function getLat()
    {
        return $this->Lat;
    }

    /**
     * Generated from protobuf field <code>double Lat = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->Lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double Lng = 3;</code>
     * @return float
     */
    public function getLng()
    {
        return $this->Lng;
    }

    /**
     * Generated from protobuf field <code>double Lng = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLng($var)
    {
        GPBUtil::checkDouble($var);
        $this->Lng = $var;

        return $this;
    }

    /**
     *搜索地址的关键字，可以不传经纬度，只传关键字
     *
     * Generated from protobuf field <code>string Keyword = 4;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->Keyword;
    }

    /**
     *搜索地址的关键字，可以不传经纬度，只传关键字
     *
     * Generated from protobuf field <code>string Keyword = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Keyword = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

