<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetWeChatsRsp.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.GetWeChatsRspMessage</code>
 */
class GetWeChatsRspMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * UID / 子账号ID
     *
     * Generated from protobuf field <code>int64 UnionId = 1;</code>
     */
    private $UnionId = 0;
    /**
     * 账号类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumAccountType AccountType = 2;</code>
     */
    private $AccountType = 0;
    /**
     * 商家Id
     *
     * Generated from protobuf field <code>int64 SupplierId = 3;</code>
     */
    private $SupplierId = 0;
    /**
     * 多个个人微信号信息
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.WeChatRspMessage WeChats = 4;</code>
     */
    private $WeChats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $UnionId
     *           UID / 子账号ID
     *     @type int $AccountType
     *           账号类型
     *     @type int|string $SupplierId
     *           商家Id
     *     @type \Jubo\JuLiao\IM\Wx\Proto\WeChatRspMessage[]|\Google\Protobuf\Internal\RepeatedField $WeChats
     *           多个个人微信号信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetWeChatsRsp::initOnce();
        parent::__construct($data);
    }

    /**
     * UID / 子账号ID
     *
     * Generated from protobuf field <code>int64 UnionId = 1;</code>
     * @return int|string
     */
    public function getUnionId()
    {
        return $this->UnionId;
    }

    /**
     * UID / 子账号ID
     *
     * Generated from protobuf field <code>int64 UnionId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->UnionId = $var;

        return $this;
    }

    /**
     * 账号类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumAccountType AccountType = 2;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->AccountType;
    }

    /**
     * 账号类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumAccountType AccountType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumAccountType::class);
        $this->AccountType = $var;

        return $this;
    }

    /**
     * 商家Id
     *
     * Generated from protobuf field <code>int64 SupplierId = 3;</code>
     * @return int|string
     */
    public function getSupplierId()
    {
        return $this->SupplierId;
    }

    /**
     * 商家Id
     *
     * Generated from protobuf field <code>int64 SupplierId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSupplierId($var)
    {
        GPBUtil::checkInt64($var);
        $this->SupplierId = $var;

        return $this;
    }

    /**
     * 多个个人微信号信息
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.WeChatRspMessage WeChats = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWeChats()
    {
        return $this->WeChats;
    }

    /**
     * 多个个人微信号信息
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.WeChatRspMessage WeChats = 4;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\WeChatRspMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWeChats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\WeChatRspMessage::class);
        $this->WeChats = $arr;

        return $this;
    }

}

