<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupMemberAddProgress.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.GroupMemberAddTaskDetailMessage</code>
 */
class GroupMemberAddTaskDetailMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信id
     *
     * Generated from protobuf field <code>string wxId = 1;</code>
     */
    private $wxId = '';
    /**
     *微信号（别名）
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     */
    private $alias = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     */
    private $nickname = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 4;</code>
     */
    private $avatar = '';
    /**
     *性别【0、女，1、男】
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     */
    private $gender = 0;
    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     */
    private $country = '';
    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 7;</code>
     */
    private $province = '';
    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 8;</code>
     */
    private $city = '';
    /**
     *更新时间
     *
     * Generated from protobuf field <code>int32 updateTime = 9;</code>
     */
    private $updateTime = 0;
    /**
     *状态【1、待发送，2、正在发送，3、已忽略，4、已发送，5、已通过】
     *
     * Generated from protobuf field <code>int32 status = 10;</code>
     */
    private $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $wxId
     *          微信id
     *     @type string $alias
     *          微信号（别名）
     *     @type string $nickname
     *          昵称
     *     @type string $avatar
     *          头像
     *     @type int $gender
     *          性别【0、女，1、男】
     *     @type string $country
     *          国家
     *     @type string $province
     *          省份
     *     @type string $city
     *          城市
     *     @type int $updateTime
     *          更新时间
     *     @type int $status
     *          状态【1、待发送，2、正在发送，3、已忽略，4、已发送，5、已通过】
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GroupMemberAddProgress::initOnce();
        parent::__construct($data);
    }

    /**
     *微信id
     *
     * Generated from protobuf field <code>string wxId = 1;</code>
     * @return string
     */
    public function getWxId()
    {
        return $this->wxId;
    }

    /**
     *微信id
     *
     * Generated from protobuf field <code>string wxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxId = $var;

        return $this;
    }

    /**
     *微信号（别名）
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     *微信号（别名）
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 4;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     *性别【0、女，1、男】
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     *性别【0、女，1、男】
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;

        return $this;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 7;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string province = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 8;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string city = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>int32 updateTime = 9;</code>
     * @return int
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     *更新时间
     *
     * Generated from protobuf field <code>int32 updateTime = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->updateTime = $var;

        return $this;
    }

    /**
     *状态【1、待发送，2、正在发送，3、已忽略，4、已发送，5、已通过】
     *
     * Generated from protobuf field <code>int32 status = 10;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *状态【1、待发送，2、正在发送，3、已忽略，4、已发送，5、已通过】
     *
     * Generated from protobuf field <code>int32 status = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

