<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupMemberAddProgress.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.GroupMemberAddProgressMessage</code>
 */
class GroupMemberAddProgressMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 任务状态【1、未开始，2、执行中，3、已暂停，4、已取消，5、已结束】
     *
     * Generated from protobuf field <code>int32 status = 1;</code>
     */
    private $status = 0;
    /**
     * 暂停类型状态【0、无，1、检测到风控自动暂停，2、手动暂停】
     *
     * Generated from protobuf field <code>int32 suspendType = 2;</code>
     */
    private $suspendType = 0;
    /**
     * 进度
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     */
    private $progress = 0.0;
    /**
     *总数量
     *
     * Generated from protobuf field <code>int32 totalQuantity = 4;</code>
     */
    private $totalQuantity = 0;
    /**
     * 待发送数量
     *
     * Generated from protobuf field <code>int32 waitSendQuantity = 5;</code>
     */
    private $waitSendQuantity = 0;
    /**
     * 发送中数量
     *
     * Generated from protobuf field <code>int32 sendingQuantity = 6;</code>
     */
    private $sendingQuantity = 0;
    /**
     * 已发送数量
     *
     * Generated from protobuf field <code>int32 sendedQuantity = 7;</code>
     */
    private $sendedQuantity = 0;
    /**
     * 已通过数量
     *
     * Generated from protobuf field <code>int32 passedQuantity = 8;</code>
     */
    private $passedQuantity = 0;
    /**
     * 已忽略数量
     *
     * Generated from protobuf field <code>int32 ignoredQuantity = 9;</code>
     */
    private $ignoredQuantity = 0;
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.GroupMemberAddTaskDetailMessage detailList = 10;</code>
     */
    private $detailList;
    /**
     * 待通过数量
     *
     * Generated from protobuf field <code>int32 waitPassedQuantity = 11;</code>
     */
    private $waitPassedQuantity = 0;
    /**
     * 未通过数量
     *
     * Generated from protobuf field <code>int32 unPassedQuantity = 12;</code>
     */
    private $unPassedQuantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *           任务状态【1、未开始，2、执行中，3、已暂停，4、已取消，5、已结束】
     *     @type int $suspendType
     *           暂停类型状态【0、无，1、检测到风控自动暂停，2、手动暂停】
     *     @type float $progress
     *           进度
     *     @type int $totalQuantity
     *          总数量
     *     @type int $waitSendQuantity
     *           待发送数量
     *     @type int $sendingQuantity
     *           发送中数量
     *     @type int $sendedQuantity
     *           已发送数量
     *     @type int $passedQuantity
     *           已通过数量
     *     @type int $ignoredQuantity
     *           已忽略数量
     *     @type \Jubo\JuLiao\IM\Wx\Proto\GroupMemberAddTaskDetailMessage[]|\Google\Protobuf\Internal\RepeatedField $detailList
     *     @type int $waitPassedQuantity
     *           待通过数量
     *     @type int $unPassedQuantity
     *           未通过数量
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GroupMemberAddProgress::initOnce();
        parent::__construct($data);
    }

    /**
     * 任务状态【1、未开始，2、执行中，3、已暂停，4、已取消，5、已结束】
     *
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 任务状态【1、未开始，2、执行中，3、已暂停，4、已取消，5、已结束】
     *
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * 暂停类型状态【0、无，1、检测到风控自动暂停，2、手动暂停】
     *
     * Generated from protobuf field <code>int32 suspendType = 2;</code>
     * @return int
     */
    public function getSuspendType()
    {
        return $this->suspendType;
    }

    /**
     * 暂停类型状态【0、无，1、检测到风控自动暂停，2、手动暂停】
     *
     * Generated from protobuf field <code>int32 suspendType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSuspendType($var)
    {
        GPBUtil::checkInt32($var);
        $this->suspendType = $var;

        return $this;
    }

    /**
     * 进度
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     * @return float
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * 进度
     *
     * Generated from protobuf field <code>double progress = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkDouble($var);
        $this->progress = $var;

        return $this;
    }

    /**
     *总数量
     *
     * Generated from protobuf field <code>int32 totalQuantity = 4;</code>
     * @return int
     */
    public function getTotalQuantity()
    {
        return $this->totalQuantity;
    }

    /**
     *总数量
     *
     * Generated from protobuf field <code>int32 totalQuantity = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalQuantity = $var;

        return $this;
    }

    /**
     * 待发送数量
     *
     * Generated from protobuf field <code>int32 waitSendQuantity = 5;</code>
     * @return int
     */
    public function getWaitSendQuantity()
    {
        return $this->waitSendQuantity;
    }

    /**
     * 待发送数量
     *
     * Generated from protobuf field <code>int32 waitSendQuantity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setWaitSendQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->waitSendQuantity = $var;

        return $this;
    }

    /**
     * 发送中数量
     *
     * Generated from protobuf field <code>int32 sendingQuantity = 6;</code>
     * @return int
     */
    public function getSendingQuantity()
    {
        return $this->sendingQuantity;
    }

    /**
     * 发送中数量
     *
     * Generated from protobuf field <code>int32 sendingQuantity = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSendingQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->sendingQuantity = $var;

        return $this;
    }

    /**
     * 已发送数量
     *
     * Generated from protobuf field <code>int32 sendedQuantity = 7;</code>
     * @return int
     */
    public function getSendedQuantity()
    {
        return $this->sendedQuantity;
    }

    /**
     * 已发送数量
     *
     * Generated from protobuf field <code>int32 sendedQuantity = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSendedQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->sendedQuantity = $var;

        return $this;
    }

    /**
     * 已通过数量
     *
     * Generated from protobuf field <code>int32 passedQuantity = 8;</code>
     * @return int
     */
    public function getPassedQuantity()
    {
        return $this->passedQuantity;
    }

    /**
     * 已通过数量
     *
     * Generated from protobuf field <code>int32 passedQuantity = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPassedQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->passedQuantity = $var;

        return $this;
    }

    /**
     * 已忽略数量
     *
     * Generated from protobuf field <code>int32 ignoredQuantity = 9;</code>
     * @return int
     */
    public function getIgnoredQuantity()
    {
        return $this->ignoredQuantity;
    }

    /**
     * 已忽略数量
     *
     * Generated from protobuf field <code>int32 ignoredQuantity = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setIgnoredQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->ignoredQuantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.GroupMemberAddTaskDetailMessage detailList = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetailList()
    {
        return $this->detailList;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.GroupMemberAddTaskDetailMessage detailList = 10;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\GroupMemberAddTaskDetailMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetailList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\GroupMemberAddTaskDetailMessage::class);
        $this->detailList = $arr;

        return $this;
    }

    /**
     * 待通过数量
     *
     * Generated from protobuf field <code>int32 waitPassedQuantity = 11;</code>
     * @return int
     */
    public function getWaitPassedQuantity()
    {
        return $this->waitPassedQuantity;
    }

    /**
     * 待通过数量
     *
     * Generated from protobuf field <code>int32 waitPassedQuantity = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setWaitPassedQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->waitPassedQuantity = $var;

        return $this;
    }

    /**
     * 未通过数量
     *
     * Generated from protobuf field <code>int32 unPassedQuantity = 12;</code>
     * @return int
     */
    public function getUnPassedQuantity()
    {
        return $this->unPassedQuantity;
    }

    /**
     * 未通过数量
     *
     * Generated from protobuf field <code>int32 unPassedQuantity = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setUnPassedQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->unPassedQuantity = $var;

        return $this;
    }

}

