<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryHbDetailTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.HbRecordMessage</code>
 */
class HbRecordMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     *
     *
     * Generated from protobuf field <code>int32 Amount = 2;</code>
     */
    private $Amount = 0;
    /**
     *
     *
     * Generated from protobuf field <code>string Time = 3;</code>
     */
    private $Time = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserName
     *          
     *     @type int $Amount
     *          
     *     @type string $Time
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryHbDetailTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 Amount = 2;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->Amount;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 Amount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Amount = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Time = 3;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->Time = $var;

        return $this;
    }

}

