<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HistoryMsgPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.HistoryMsgPushNoticeMessage</code>
 */
class HistoryMsgPushNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ChatMessage Messages = 2;</code>
     */
    private $Messages;
    /**
     * 页大小，固定50
     *
     * Generated from protobuf field <code>int32 Size = 3;</code>
     */
    private $Size = 0;
    /**
     * 总数，只在获取单个会话时有用，获取全部会话的时候不准确
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     */
    private $Count = 0;
    /**
     * 页码，从0开始
     *
     * Generated from protobuf field <code>int32 Page = 5;</code>
     */
    private $Page = 0;
    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type \Jubo\JuLiao\IM\Wx\Proto\ChatMessage[]|\Google\Protobuf\Internal\RepeatedField $Messages
     *     @type int $Size
     *           页大小，固定50
     *     @type int $Count
     *           总数，只在获取单个会话时有用，获取全部会话的时候不准确
     *     @type int $Page
     *           页码，从0开始
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\HistoryMsgPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ChatMessage Messages = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->Messages;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ChatMessage Messages = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\ChatMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\ChatMessage::class);
        $this->Messages = $arr;

        return $this;
    }

    /**
     * 页大小，固定50
     *
     * Generated from protobuf field <code>int32 Size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->Size;
    }

    /**
     * 页大小，固定50
     *
     * Generated from protobuf field <code>int32 Size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->Size = $var;

        return $this;
    }

    /**
     * 总数，只在获取单个会话时有用，获取全部会话的时候不准确
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * 总数，只在获取单个会话时有用，获取全部会话的时候不准确
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * 页码，从0开始
     *
     * Generated from protobuf field <code>int32 Page = 5;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->Page;
    }

    /**
     * 页码，从0开始
     *
     * Generated from protobuf field <code>int32 Page = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->Page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

