<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinGroupByQrTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.JoinGroupByQrTaskMessage</code>
 */
class JoinGroupByQrTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrUrl = 2;</code>
     */
    private $QrUrl = '';
    /**
     * 二维码解析后的内容，与QrUrl二选一
     *
     * Generated from protobuf field <code>string QrContent = 3;</code>
     */
    private $QrContent = '';
    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type string $QrUrl
     *           二维码图片url
     *     @type string $QrContent
     *           二维码解析后的内容，与QrUrl二选一
     *     @type int|string $TaskId
     *           任务ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\JoinGroupByQrTask::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrUrl = 2;</code>
     * @return string
     */
    public function getQrUrl()
    {
        return $this->QrUrl;
    }

    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQrUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->QrUrl = $var;

        return $this;
    }

    /**
     * 二维码解析后的内容，与QrUrl二选一
     *
     * Generated from protobuf field <code>string QrContent = 3;</code>
     * @return string
     */
    public function getQrContent()
    {
        return $this->QrContent;
    }

    /**
     * 二维码解析后的内容，与QrUrl二选一
     *
     * Generated from protobuf field <code>string QrContent = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQrContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->QrContent = $var;

        return $this;
    }

    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

