<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactLabelInfoNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessage</code>
 */
class LabelInfoMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 LabelId = 1;</code>
     */
    private $LabelId = 0;
    /**
     * Generated from protobuf field <code>string LabelName = 2;</code>
     */
    private $LabelName = '';
    /**
     * Generated from protobuf field <code>int64 CreateTime = 3;</code>
     */
    private $CreateTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $LabelId
     *     @type string $LabelName
     *     @type int|string $CreateTime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ContactLabelInfoNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 LabelId = 1;</code>
     * @return int
     */
    public function getLabelId()
    {
        return $this->LabelId;
    }

    /**
     * Generated from protobuf field <code>int32 LabelId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLabelId($var)
    {
        GPBUtil::checkInt32($var);
        $this->LabelId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LabelName = 2;</code>
     * @return string
     */
    public function getLabelName()
    {
        return $this->LabelName;
    }

    /**
     * Generated from protobuf field <code>string LabelName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LabelName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 3;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

}

