<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSendHistoryPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.MassMessage</code>
 */
class MassMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 群发收件人列表
     *
     * Generated from protobuf field <code>string ToList = 1;</code>
     */
    private $ToList = '';
    /**
     * 收件人数量
     *
     * Generated from protobuf field <code>int32 ToCount = 2;</code>
     */
    private $ToCount = 0;
    /**
     * 发送的消息类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     */
    private $ContentType = 0;
    /**
     * 内容
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     */
    private $Content = '';
    /**
     * 发送时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 5;</code>
     */
    private $CreateTime = 0;
    /**
     *
     *
     * Generated from protobuf field <code>int32 Status = 6;</code>
     */
    private $Status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ToList
     *           群发收件人列表
     *     @type int $ToCount
     *           收件人数量
     *     @type int $ContentType
     *           发送的消息类型
     *     @type string $Content
     *           内容
     *     @type int|string $CreateTime
     *           发送时间
     *     @type int $Status
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GroupSendHistoryPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 群发收件人列表
     *
     * Generated from protobuf field <code>string ToList = 1;</code>
     * @return string
     */
    public function getToList()
    {
        return $this->ToList;
    }

    /**
     * 群发收件人列表
     *
     * Generated from protobuf field <code>string ToList = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToList($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToList = $var;

        return $this;
    }

    /**
     * 收件人数量
     *
     * Generated from protobuf field <code>int32 ToCount = 2;</code>
     * @return int
     */
    public function getToCount()
    {
        return $this->ToCount;
    }

    /**
     * 收件人数量
     *
     * Generated from protobuf field <code>int32 ToCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setToCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->ToCount = $var;

        return $this;
    }

    /**
     * 发送的消息类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     * 发送的消息类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumContentType::class);
        $this->ContentType = $var;

        return $this;
    }

    /**
     * 内容
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 内容
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     * 发送时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 5;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     * 发送时间
     *
     * Generated from protobuf field <code>int64 CreateTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 Status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 Status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->Status = $var;

        return $this;
    }

}

