<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SphMentionListNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.MentionMessage</code>
 */
class MentionMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.SphBriefMessage SphItem = 1;</code>
     */
    protected $SphItem = null;
    /**
     * Generated from protobuf field <code>int64 Id = 2;</code>
     */
    protected $Id = 0;
    /**
     * Generated from protobuf field <code>int32 Type = 3;</code>
     */
    protected $Type = 0;
    /**
     * Generated from protobuf field <code>int64 MentionId = 4;</code>
     */
    protected $MentionId = 0;
    /**
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     */
    protected $CommentId = 0;
    /**
     * Generated from protobuf field <code>string UserName = 6;</code>
     */
    protected $UserName = '';
    /**
     * Generated from protobuf field <code>string NickName = 7;</code>
     */
    protected $NickName = '';
    /**
     * Generated from protobuf field <code>string Avatar = 8;</code>
     */
    protected $Avatar = '';
    /**
     * 评论内容
     *
     * Generated from protobuf field <code>string Content = 9;</code>
     */
    protected $Content = '';
    /**
     * Generated from protobuf field <code>int32 ContentType = 10;</code>
     */
    protected $ContentType = 0;
    /**
     *
     *
     * Generated from protobuf field <code>int32 CreateTime = 11;</code>
     */
    protected $CreateTime = 0;
    /**
     *
     *
     * Generated from protobuf field <code>string ReplayUsername = 12;</code>
     */
    protected $ReplayUsername = '';
    /**
     *
     *
     * Generated from protobuf field <code>string ReplayNickname = 13;</code>
     */
    protected $ReplayNickname = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 RootCommentId = 14;</code>
     */
    protected $RootCommentId = 0;
    /**
     * Generated from protobuf field <code>string refContent = 15;</code>
     */
    protected $refContent = '';
    /**
     * Generated from protobuf field <code>int64 FansId = 16;</code>
     */
    protected $FansId = 0;
    /**
     * Generated from protobuf field <code>int64 FollowId = 17;</code>
     */
    protected $FollowId = 0;
    /**
     * Generated from protobuf field <code>int32 RelationType = 18;</code>
     */
    protected $RelationType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jubo\JuLiao\IM\Wx\Proto\SphBriefMessage $SphItem
     *     @type int|string $Id
     *     @type int $Type
     *     @type int|string $MentionId
     *     @type int|string $CommentId
     *     @type string $UserName
     *     @type string $NickName
     *     @type string $Avatar
     *     @type string $Content
     *           评论内容
     *     @type int $ContentType
     *     @type int $CreateTime
     *          
     *     @type string $ReplayUsername
     *          
     *     @type string $ReplayNickname
     *          
     *     @type int|string $RootCommentId
     *          
     *     @type string $refContent
     *     @type int|string $FansId
     *     @type int|string $FollowId
     *     @type int $RelationType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SphMentionListNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.SphBriefMessage SphItem = 1;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\SphBriefMessage|null
     */
    public function getSphItem()
    {
        return $this->SphItem;
    }

    public function hasSphItem()
    {
        return isset($this->SphItem);
    }

    public function clearSphItem()
    {
        unset($this->SphItem);
    }

    /**
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.SphBriefMessage SphItem = 1;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\SphBriefMessage $var
     * @return $this
     */
    public function setSphItem($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\SphBriefMessage::class);
        $this->SphItem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 MentionId = 4;</code>
     * @return int|string
     */
    public function getMentionId()
    {
        return $this->MentionId;
    }

    /**
     * Generated from protobuf field <code>int64 MentionId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMentionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MentionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     * @return int|string
     */
    public function getCommentId()
    {
        return $this->CommentId;
    }

    /**
     * Generated from protobuf field <code>int64 CommentId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommentId($var)
    {
        GPBUtil::checkInt64($var);
        $this->CommentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserName = 6;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string NickName = 7;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * Generated from protobuf field <code>string NickName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Avatar = 8;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     * Generated from protobuf field <code>string Avatar = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * 评论内容
     *
     * Generated from protobuf field <code>string Content = 9;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 评论内容
     *
     * Generated from protobuf field <code>string Content = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ContentType = 10;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     * Generated from protobuf field <code>int32 ContentType = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkInt32($var);
        $this->ContentType = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 CreateTime = 11;</code>
     * @return int
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 CreateTime = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string ReplayUsername = 12;</code>
     * @return string
     */
    public function getReplayUsername()
    {
        return $this->ReplayUsername;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string ReplayUsername = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setReplayUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReplayUsername = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string ReplayNickname = 13;</code>
     * @return string
     */
    public function getReplayNickname()
    {
        return $this->ReplayNickname;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string ReplayNickname = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setReplayNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReplayNickname = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 RootCommentId = 14;</code>
     * @return int|string
     */
    public function getRootCommentId()
    {
        return $this->RootCommentId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 RootCommentId = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRootCommentId($var)
    {
        GPBUtil::checkInt64($var);
        $this->RootCommentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string refContent = 15;</code>
     * @return string
     */
    public function getRefContent()
    {
        return $this->refContent;
    }

    /**
     * Generated from protobuf field <code>string refContent = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setRefContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->refContent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 FansId = 16;</code>
     * @return int|string
     */
    public function getFansId()
    {
        return $this->FansId;
    }

    /**
     * Generated from protobuf field <code>int64 FansId = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFansId($var)
    {
        GPBUtil::checkInt64($var);
        $this->FansId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 FollowId = 17;</code>
     * @return int|string
     */
    public function getFollowId()
    {
        return $this->FollowId;
    }

    /**
     * Generated from protobuf field <code>int64 FollowId = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkInt64($var);
        $this->FollowId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 RelationType = 18;</code>
     * @return int
     */
    public function getRelationType()
    {
        return $this->RelationType;
    }

    /**
     * Generated from protobuf field <code>int32 RelationType = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setRelationType($var)
    {
        GPBUtil::checkInt32($var);
        $this->RelationType = $var;

        return $this;
    }

}

