<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModifyFriendMemoTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ModifyFriendMemoTaskMessage</code>
 */
class ModifyFriendMemoTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 联系人微信号
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     * 备注
     *
     * Generated from protobuf field <code>string Memo = 3;</code>
     */
    private $Memo = '';
    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;
    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 5;</code>
     */
    private $Desc = '';
    /**
     * 电话号码
     *
     * Generated from protobuf field <code>string Phone = 6;</code>
     */
    private $Phone = '';
    /**
     * 删除标志  1 删除备注 2 删除描述 4 删除号码；可组合
     *
     * Generated from protobuf field <code>int32 DelFlag = 7;</code>
     */
    private $DelFlag = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type string $FriendId
     *           联系人微信号
     *     @type string $Memo
     *           备注
     *     @type int|string $TaskId
     *           任务ID
     *     @type string $Desc
     *           描述
     *     @type string $Phone
     *           电话号码
     *     @type int $DelFlag
     *           删除标志  1 删除备注 2 删除描述 4 删除号码；可组合
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModifyFriendMemoTask::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 联系人微信号
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 联系人微信号
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Memo = 3;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->Memo;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Memo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->Memo = $var;

        return $this;
    }

    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 5;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->Desc;
    }

    /**
     * 描述
     *
     * Generated from protobuf field <code>string Desc = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->Desc = $var;

        return $this;
    }

    /**
     * 电话号码
     *
     * Generated from protobuf field <code>string Phone = 6;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->Phone;
    }

    /**
     * 电话号码
     *
     * Generated from protobuf field <code>string Phone = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->Phone = $var;

        return $this;
    }

    /**
     * 删除标志  1 删除备注 2 删除描述 4 删除号码；可组合
     *
     * Generated from protobuf field <code>int32 DelFlag = 7;</code>
     * @return int
     */
    public function getDelFlag()
    {
        return $this->DelFlag;
    }

    /**
     * 删除标志  1 删除备注 2 删除描述 4 删除号码；可组合
     *
     * Generated from protobuf field <code>int32 DelFlag = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDelFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->DelFlag = $var;

        return $this;
    }

}

