<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDelNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.MsgDelNoticeMessage</code>
 */
class MsgDelNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 会话Id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     */
    private $FriendId = '';
    /**
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     */
    private $IsSend = false;
    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     */
    private $ContentType = 0;
    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     */
    private $Content = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     */
    private $MsgId = 0;
    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     */
    private $msgSvrId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type string $FriendId
     *           会话Id
     *     @type bool $IsSend
     *     @type int $ContentType
     *           发送的消息内容类型
     *     @type string $Content
     *           内容 二进制流
     *     @type int|string $MsgId
     *          
     *     @type int|string $msgSvrId
     *           消息唯一id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MsgDelNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 会话Id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 会话Id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     * @return bool
     */
    public function getIsSend()
    {
        return $this->IsSend;
    }

    /**
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSend($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSend = $var;

        return $this;
    }

    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     * 发送的消息内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumContentType::class);
        $this->ContentType = $var;

        return $this;
    }

    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 内容 二进制流
     *
     * Generated from protobuf field <code>bytes Content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->msgSvrId;
    }

    /**
     * 消息唯一id
     *
     * Generated from protobuf field <code>int64 msgSvrId = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgSvrId = $var;

        return $this;
    }

}

