<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OneKeyLikeTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.OneKeyLikeTaskResultNoticeMessage</code>
 */
class OneKeyLikeTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     */
    private $TaskId = 0;
    /**
     * 已点赞数量
     *
     * Generated from protobuf field <code>int32 Count = 3;</code>
     */
    private $Count = 0;
    /**
     *结束方式，0 正常 1 到达上次点赞位置 2 到达最大点赞数 3 朋友圈到底 4 任务超时
     *
     * Generated from protobuf field <code>int32 EndType = 4;</code>
     */
    private $EndType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type int|string $TaskId
     *           所执行的任务ID
     *     @type int $Count
     *           已点赞数量
     *     @type int $EndType
     *          结束方式，0 正常 1 到达上次点赞位置 2 到达最大点赞数 3 朋友圈到底 4 任务超时
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OneKeyLikeTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 所执行的任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 已点赞数量
     *
     * Generated from protobuf field <code>int32 Count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * 已点赞数量
     *
     * Generated from protobuf field <code>int32 Count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     *结束方式，0 正常 1 到达上次点赞位置 2 到达最大点赞数 3 朋友圈到底 4 任务超时
     *
     * Generated from protobuf field <code>int32 EndType = 4;</code>
     * @return int
     */
    public function getEndType()
    {
        return $this->EndType;
    }

    /**
     *结束方式，0 正常 1 到达上次点赞位置 2 到达最大点赞数 3 朋友圈到底 4 任务超时
     *
     * Generated from protobuf field <code>int32 EndType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndType($var)
    {
        GPBUtil::checkInt32($var);
        $this->EndType = $var;

        return $this;
    }

}

