<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhoneStateTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PhoneStateTaskMessage</code>
 */
class PhoneStateTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * WechatId和imei用于服务端选择通道，对客户端无用
     *
     * Generated from protobuf field <code>string Imei = 2;</code>
     */
    private $Imei = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type string $Imei
     *           WechatId和imei用于服务端选择通道，对客户端无用
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PhoneStateTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * WechatId和imei用于服务端选择通道，对客户端无用
     *
     * Generated from protobuf field <code>string Imei = 2;</code>
     * @return string
     */
    public function getImei()
    {
        return $this->Imei;
    }

    /**
     * WechatId和imei用于服务端选择通道，对客户端无用
     *
     * Generated from protobuf field <code>string Imei = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImei($var)
    {
        GPBUtil::checkString($var, True);
        $this->Imei = $var;

        return $this;
    }

}

