<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

if (false) {
    /**
     * This class is deprecated. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\VisibleMessage\EnumVisibleType instead.
     * @deprecated
     */
    class PostSNSNewsTaskMessage_VisibleMessage_EnumVisibleType {}
}
class_exists(PostSNSNewsTaskMessage\VisibleMessage\EnumVisibleType::class);
@trigger_error('Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage_VisibleMessage_EnumVisibleType is deprecated and will be removed in the next major release. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\VisibleMessage\EnumVisibleType instead', E_USER_DEPRECATED);

