<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

if (false) {
    /**
     * This class is deprecated. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\PoiMessage instead.
     * @deprecated
     */
    class PostSNSNewsTaskMessage_PoiMessage {}
}
class_exists(PostSNSNewsTaskMessage\PoiMessage::class);
@trigger_error('Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage_PoiMessage is deprecated and will be removed in the next major release. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\PoiMessage instead', E_USER_DEPRECATED);

