<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

if (false) {
    /**
     * This class is deprecated. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\VisibleMessage instead.
     * @deprecated
     */
    class PostSNSNewsTaskMessage_VisibleMessage {}
}
class_exists(PostSNSNewsTaskMessage\VisibleMessage::class);
@trigger_error('Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage_VisibleMessage is deprecated and will be removed in the next major release. Use Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\VisibleMessage instead', E_USER_DEPRECATED);

