<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostFriendDetectTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PostFriendDetectTaskMessage</code>
 */
class PostFriendDetectTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 微信id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 清粉任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     */
    private $TaskId = 0;
    /**
     * 消息内容（内容为空时发空名片，对方无感知；不为空则发送文本消息，对方能收到）
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     */
    private $Message = '';
    /**
     * false 检测到立即删除，true 不删除，通知到服务端
     *
     * Generated from protobuf field <code>bool OnlyCheck = 4;</code>
     */
    private $OnlyCheck = false;
    /**
     * 跳过多少小时内有互动的好友（聊天，朋友圈互动,上次已检测等），缺省72小时
     *
     * Generated from protobuf field <code>int32 SkipHour = 5;</code>
     */
    private $SkipHour = 0;
    /**
     * &01 不检测朋友圈 (废弃，改进后朋友圈检测效率提高）
     *
     * Generated from protobuf field <code>int32 Mode = 6;</code>
     */
    private $Mode = 0;
    /**
     * 检测最大人数（不包括跳过检测的，配合SkipHour可以将整个清粉动作分成几天完成）
     *
     * Generated from protobuf field <code>int32 Max = 7;</code>
     */
    private $Max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           微信id
     *     @type int|string $TaskId
     *           清粉任务ID
     *     @type string $Message
     *           消息内容（内容为空时发空名片，对方无感知；不为空则发送文本消息，对方能收到）
     *     @type bool $OnlyCheck
     *           false 检测到立即删除，true 不删除，通知到服务端
     *     @type int $SkipHour
     *           跳过多少小时内有互动的好友（聊天，朋友圈互动,上次已检测等），缺省72小时
     *     @type int $Mode
     *           &01 不检测朋友圈 (废弃，改进后朋友圈检测效率提高）
     *     @type int $Max
     *           检测最大人数（不包括跳过检测的，配合SkipHour可以将整个清粉动作分成几天完成）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PostFriendDetectTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 微信id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 微信id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 清粉任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 清粉任务ID
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * 消息内容（内容为空时发空名片，对方无感知；不为空则发送文本消息，对方能收到）
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * 消息内容（内容为空时发空名片，对方无感知；不为空则发送文本消息，对方能收到）
     *
     * Generated from protobuf field <code>string Message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * false 检测到立即删除，true 不删除，通知到服务端
     *
     * Generated from protobuf field <code>bool OnlyCheck = 4;</code>
     * @return bool
     */
    public function getOnlyCheck()
    {
        return $this->OnlyCheck;
    }

    /**
     * false 检测到立即删除，true 不删除，通知到服务端
     *
     * Generated from protobuf field <code>bool OnlyCheck = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setOnlyCheck($var)
    {
        GPBUtil::checkBool($var);
        $this->OnlyCheck = $var;

        return $this;
    }

    /**
     * 跳过多少小时内有互动的好友（聊天，朋友圈互动,上次已检测等），缺省72小时
     *
     * Generated from protobuf field <code>int32 SkipHour = 5;</code>
     * @return int
     */
    public function getSkipHour()
    {
        return $this->SkipHour;
    }

    /**
     * 跳过多少小时内有互动的好友（聊天，朋友圈互动,上次已检测等），缺省72小时
     *
     * Generated from protobuf field <code>int32 SkipHour = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSkipHour($var)
    {
        GPBUtil::checkInt32($var);
        $this->SkipHour = $var;

        return $this;
    }

    /**
     * &01 不检测朋友圈 (废弃，改进后朋友圈检测效率提高）
     *
     * Generated from protobuf field <code>int32 Mode = 6;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     * &01 不检测朋友圈 (废弃，改进后朋友圈检测效率提高）
     *
     * Generated from protobuf field <code>int32 Mode = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkInt32($var);
        $this->Mode = $var;

        return $this;
    }

    /**
     * 检测最大人数（不包括跳过检测的，配合SkipHour可以将整个清粉动作分成几天完成）
     *
     * Generated from protobuf field <code>int32 Max = 7;</code>
     * @return int
     */
    public function getMax()
    {
        return $this->Max;
    }

    /**
     * 检测最大人数（不包括跳过检测的，配合SkipHour可以将整个清粉动作分成几天完成）
     *
     * Generated from protobuf field <code>int32 Max = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->Max = $var;

        return $this;
    }

}

