<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskResultNoticeMessage</code>
 */
class PostSNSNewsTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     */
    private $Success = false;
    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    private $Code = 0;
    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     */
    private $ErrMsg = '';
    /**
     * 业务的id,通用的。   
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;
    /**
     *扩展信息（手机端不用考虑）
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskResultNoticeMessage.ExtraProperties Extra = 7;</code>
     */
    private $Extra = null;
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 8;</code>
     */
    private $WeChatId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Success
     *           是否成功
     *     @type int $Code
     *           错误码 Success = true 忽略
     *     @type string $ErrMsg
     *           错误内容描述 Success = true 忽略
     *     @type int|string $TaskId
     *           业务的id,通用的。   
     *     @type \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskResultNoticeMessage\ExtraProperties $Extra
     *          扩展信息（手机端不用考虑）
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PostSNSNewsTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumErrorCode::class);
        $this->Code = $var;

        return $this;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误内容描述 Success = true 忽略
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

    /**
     * 业务的id,通用的。   
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 业务的id,通用的。   
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     *扩展信息（手机端不用考虑）
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskResultNoticeMessage.ExtraProperties Extra = 7;</code>
     * @return \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskResultNoticeMessage\ExtraProperties
     */
    public function getExtra()
    {
        return $this->Extra;
    }

    /**
     *扩展信息（手机端不用考虑）
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskResultNoticeMessage.ExtraProperties Extra = 7;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskResultNoticeMessage\ExtraProperties $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkMessage($var, \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskResultNoticeMessage_ExtraProperties::class);
        $this->Extra = $var;

        return $this;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 8;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

}

