<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullSmsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PullSmsTaskMessage</code>
 */
class PullSmsTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 设备id
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     */
    private $IMEI = '';
    /**
     * 起始时间，UTC
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     */
    private $StartTime = 0;
    /**
     * 结束时间，0为当前时间 UTC
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     */
    private $EndTime = 0;
    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $IMEI
     *           设备id
     *     @type int|string $StartTime
     *           起始时间，UTC
     *     @type int|string $EndTime
     *           结束时间，0为当前时间 UTC
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PullSmsTask::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 设备id
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * 设备id
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     * 起始时间，UTC
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 起始时间，UTC
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 结束时间，0为当前时间 UTC
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 结束时间，0为当前时间 UTC
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

