<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullFriendCircleTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PullFriendCircleTaskMessage</code>
 */
class PullFriendCircleTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 获取好友的朋友圈,传空则返回所有人
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     * 废弃 //UTC秒，小于该时间，用于向下翻页
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     */
    private $StartTime = 0;
    /**
     * 废弃，微信每页获取10条  //最多条数，缺省20条
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     */
    private $Count = 0;
    /**
     * 废弃 //UTC秒，大于该时间，用于向上翻页
     *
     * Generated from protobuf field <code>int64 RefTime = 5;</code>
     */
    private $RefTime = 0;
    /**
     * 首次传0，获取下一页传上一页最后一条的snsid
     *
     * Generated from protobuf field <code>int64 RefSnsId = 6;</code>
     */
    private $RefSnsId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信
     *     @type string $FriendId
     *           获取好友的朋友圈,传空则返回所有人
     *     @type int|string $StartTime
     *           废弃 //UTC秒，小于该时间，用于向下翻页
     *     @type int $Count
     *           废弃，微信每页获取10条  //最多条数，缺省20条
     *     @type int|string $RefTime
     *           废弃 //UTC秒，大于该时间，用于向上翻页
     *     @type int|string $RefSnsId
     *           首次传0，获取下一页传上一页最后一条的snsid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PullFriendCircleTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 获取好友的朋友圈,传空则返回所有人
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 获取好友的朋友圈,传空则返回所有人
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * 废弃 //UTC秒，小于该时间，用于向下翻页
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 废弃 //UTC秒，小于该时间，用于向下翻页
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 废弃，微信每页获取10条  //最多条数，缺省20条
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * 废弃，微信每页获取10条  //最多条数，缺省20条
     *
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * 废弃 //UTC秒，大于该时间，用于向上翻页
     *
     * Generated from protobuf field <code>int64 RefTime = 5;</code>
     * @return int|string
     */
    public function getRefTime()
    {
        return $this->RefTime;
    }

    /**
     * 废弃 //UTC秒，大于该时间，用于向上翻页
     *
     * Generated from protobuf field <code>int64 RefTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->RefTime = $var;

        return $this;
    }

    /**
     * 首次传0，获取下一页传上一页最后一条的snsid
     *
     * Generated from protobuf field <code>int64 RefSnsId = 6;</code>
     * @return int|string
     */
    public function getRefSnsId()
    {
        return $this->RefSnsId;
    }

    /**
     * 首次传0，获取下一页传上一页最后一条的snsid
     *
     * Generated from protobuf field <code>int64 RefSnsId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefSnsId($var)
    {
        GPBUtil::checkInt64($var);
        $this->RefSnsId = $var;

        return $this;
    }

}

