<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullEmojiInfoTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PullEmojiInfoTaskResultNoticeMessage</code>
 */
class PullEmojiInfoTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     */
    private $TaskId = 0;
    /**
     * emojiInfo列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.EmojiMessage Emojis = 3;</code>
     */
    private $Emojis;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家个人微信内部全局唯一识别码
     *     @type int|string $TaskId
     *           业务的id,通用的。
     *     @type \Jubo\JuLiao\IM\Wx\Proto\EmojiMessage[]|\Google\Protobuf\Internal\RepeatedField $Emojis
     *           emojiInfo列表
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PullEmojiInfoTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家个人微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * emojiInfo列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.EmojiMessage Emojis = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmojis()
    {
        return $this->Emojis;
    }

    /**
     * emojiInfo列表
     *
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.EmojiMessage Emojis = 3;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\EmojiMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmojis($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\EmojiMessage::class);
        $this->Emojis = $arr;

        return $this;
    }

}

