<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullWeChatQrCodeTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.PullWeChatQrCodeTaskResultNoticeMessage</code>
 */
class PullWeChatQrCodeTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrCodeUrl = 2;</code>
     */
    private $QrCodeUrl = '';
    /**
     * Generated from protobuf field <code>bool Success = 3;</code>
     */
    private $Success = false;
    /**
     * 错误信息 or 二维码过期提示
     *
     * Generated from protobuf field <code>string ErrMsg = 4;</code>
     */
    private $ErrMsg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $QrCodeUrl
     *           二维码图片url
     *     @type bool $Success
     *     @type string $ErrMsg
     *           错误信息 or 二维码过期提示
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PullWeChatQrCodeTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrCodeUrl = 2;</code>
     * @return string
     */
    public function getQrCodeUrl()
    {
        return $this->QrCodeUrl;
    }

    /**
     * 二维码图片url
     *
     * Generated from protobuf field <code>string QrCodeUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQrCodeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->QrCodeUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Success = 3;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * Generated from protobuf field <code>bool Success = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误信息 or 二维码过期提示
     *
     * Generated from protobuf field <code>string ErrMsg = 4;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误信息 or 二维码过期提示
     *
     * Generated from protobuf field <code>string ErrMsg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

}

