<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryHbDetailTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.QueryHbDetailTaskMessage</code>
 */
class QueryHbDetailTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 红包key
     *
     * Generated from protobuf field <code>string HbUrl = 2;</code>
     */
    private $HbUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信号
     *     @type string $HbUrl
     *           红包key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryHbDetailTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 红包key
     *
     * Generated from protobuf field <code>string HbUrl = 2;</code>
     * @return string
     */
    public function getHbUrl()
    {
        return $this->HbUrl;
    }

    /**
     * 红包key
     *
     * Generated from protobuf field <code>string HbUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHbUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->HbUrl = $var;

        return $this;
    }

}

