<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QwConversPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.QwConversMessage</code>
 */
class QwConversMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 全局唯一识别码
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     * 消息概要显示
     *
     * Generated from protobuf field <code>string Digest = 2;</code>
     */
    private $Digest = '';
    /**
     * 最后消息是否自己发送
     *
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     */
    private $IsSend = false;
    /**
     * 消息条数
     *
     * Generated from protobuf field <code>int32 MsgCnt = 5;</code>
     */
    private $MsgCnt = 0;
    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 6;</code>
     */
    private $UnreadCnt = 0;
    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 7;</code>
     */
    private $UpdateTime = 0;
    /**
     * 是否置顶
     *
     * Generated from protobuf field <code>bool IsTop = 8;</code>
     */
    private $IsTop = false;
    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 9;</code>
     */
    private $IsSilent = false;
    /**
     *int32 ChatMode = 10; //是否可以发消息
     *
     * Generated from protobuf field <code>string ShowName = 11;</code>
     */
    private $ShowName = '';
    /**
     * 头像
     *
     * Generated from protobuf field <code>string Avatar = 12;</code>
     */
    private $Avatar = '';
    /**
     * Generated from protobuf field <code>int32 AtCount = 13;</code>
     */
    private $AtCount = 0;
    /**
     *上级会话
     *
     * Generated from protobuf field <code>string Parent = 14;</code>
     */
    private $Parent = '';
    /**
     *上级会话名称
     *
     * Generated from protobuf field <code>string ParentName = 15;</code>
     */
    private $ParentName = '';
    /**
     *群主 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string Owner = 16;</code>
     */
    private $Owner = '';
    /**
     *群聊成员 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string UserList = 17;</code>
     */
    private $UserList = '';
    /**
     *
     *
     * Generated from protobuf field <code>int32 RoomFlag = 18;</code>
     */
    private $RoomFlag = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserName
     *           全局唯一识别码
     *     @type string $Digest
     *           消息概要显示
     *     @type bool $IsSend
     *           最后消息是否自己发送
     *     @type int $MsgCnt
     *           消息条数
     *     @type int $UnreadCnt
     *           未读消息条数
     *     @type int|string $UpdateTime
     *           最后消息的时间
     *     @type bool $IsTop
     *           是否置顶
     *     @type bool $IsSilent
     *           是否消息免打扰
     *     @type string $ShowName
     *          int32 ChatMode = 10; //是否可以发消息
     *     @type string $Avatar
     *           头像
     *     @type int $AtCount
     *     @type string $Parent
     *          上级会话
     *     @type string $ParentName
     *          上级会话名称
     *     @type string $Owner
     *          群主 (业务未明确，暂时不传）
     *     @type string $UserList
     *          群聊成员 (业务未明确，暂时不传）
     *     @type int $RoomFlag
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QwConversPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 全局唯一识别码
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * 全局唯一识别码
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * 消息概要显示
     *
     * Generated from protobuf field <code>string Digest = 2;</code>
     * @return string
     */
    public function getDigest()
    {
        return $this->Digest;
    }

    /**
     * 消息概要显示
     *
     * Generated from protobuf field <code>string Digest = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDigest($var)
    {
        GPBUtil::checkString($var, True);
        $this->Digest = $var;

        return $this;
    }

    /**
     * 最后消息是否自己发送
     *
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     * @return bool
     */
    public function getIsSend()
    {
        return $this->IsSend;
    }

    /**
     * 最后消息是否自己发送
     *
     * Generated from protobuf field <code>bool IsSend = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSend($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSend = $var;

        return $this;
    }

    /**
     * 消息条数
     *
     * Generated from protobuf field <code>int32 MsgCnt = 5;</code>
     * @return int
     */
    public function getMsgCnt()
    {
        return $this->MsgCnt;
    }

    /**
     * 消息条数
     *
     * Generated from protobuf field <code>int32 MsgCnt = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgCnt($var)
    {
        GPBUtil::checkInt32($var);
        $this->MsgCnt = $var;

        return $this;
    }

    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 6;</code>
     * @return int
     */
    public function getUnreadCnt()
    {
        return $this->UnreadCnt;
    }

    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUnreadCnt($var)
    {
        GPBUtil::checkInt32($var);
        $this->UnreadCnt = $var;

        return $this;
    }

    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 7;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->UpdateTime;
    }

    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->UpdateTime = $var;

        return $this;
    }

    /**
     * 是否置顶
     *
     * Generated from protobuf field <code>bool IsTop = 8;</code>
     * @return bool
     */
    public function getIsTop()
    {
        return $this->IsTop;
    }

    /**
     * 是否置顶
     *
     * Generated from protobuf field <code>bool IsTop = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTop($var)
    {
        GPBUtil::checkBool($var);
        $this->IsTop = $var;

        return $this;
    }

    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 9;</code>
     * @return bool
     */
    public function getIsSilent()
    {
        return $this->IsSilent;
    }

    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSilent($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSilent = $var;

        return $this;
    }

    /**
     *int32 ChatMode = 10; //是否可以发消息
     *
     * Generated from protobuf field <code>string ShowName = 11;</code>
     * @return string
     */
    public function getShowName()
    {
        return $this->ShowName;
    }

    /**
     *int32 ChatMode = 10; //是否可以发消息
     *
     * Generated from protobuf field <code>string ShowName = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setShowName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShowName = $var;

        return $this;
    }

    /**
     * 头像
     *
     * Generated from protobuf field <code>string Avatar = 12;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     * 头像
     *
     * Generated from protobuf field <code>string Avatar = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 AtCount = 13;</code>
     * @return int
     */
    public function getAtCount()
    {
        return $this->AtCount;
    }

    /**
     * Generated from protobuf field <code>int32 AtCount = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setAtCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->AtCount = $var;

        return $this;
    }

    /**
     *上级会话
     *
     * Generated from protobuf field <code>string Parent = 14;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->Parent;
    }

    /**
     *上级会话
     *
     * Generated from protobuf field <code>string Parent = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Parent = $var;

        return $this;
    }

    /**
     *上级会话名称
     *
     * Generated from protobuf field <code>string ParentName = 15;</code>
     * @return string
     */
    public function getParentName()
    {
        return $this->ParentName;
    }

    /**
     *上级会话名称
     *
     * Generated from protobuf field <code>string ParentName = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setParentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentName = $var;

        return $this;
    }

    /**
     *群主 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string Owner = 16;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->Owner;
    }

    /**
     *群主 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string Owner = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->Owner = $var;

        return $this;
    }

    /**
     *群聊成员 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string UserList = 17;</code>
     * @return string
     */
    public function getUserList()
    {
        return $this->UserList;
    }

    /**
     *群聊成员 (业务未明确，暂时不传）
     *
     * Generated from protobuf field <code>string UserList = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setUserList($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserList = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 RoomFlag = 18;</code>
     * @return int
     */
    public function getRoomFlag()
    {
        return $this->RoomFlag;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int32 RoomFlag = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setRoomFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->RoomFlag = $var;

        return $this;
    }

}

