<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QwConversPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.QwConversPushNoticeMessage</code>
 */
class QwConversPushNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 客服个微全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.QwConversMessage Convers = 2;</code>
     */
    private $Convers;
    /**
     * Generated from protobuf field <code>int32 Size = 3;</code>
     */
    private $Size = 0;
    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     */
    private $Count = 0;
    /**
     * Generated from protobuf field <code>int32 Page = 5;</code>
     */
    private $Page = 0;
    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           客服个微全局唯一识别码
     *     @type \Jubo\JuLiao\IM\Wx\Proto\QwConversMessage[]|\Google\Protobuf\Internal\RepeatedField $Convers
     *     @type int $Size
     *     @type int $Count
     *     @type int $Page
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QwConversPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 客服个微全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 客服个微全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.QwConversMessage Convers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConvers()
    {
        return $this->Convers;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.QwConversMessage Convers = 2;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\QwConversMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConvers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\QwConversMessage::class);
        $this->Convers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->Size;
    }

    /**
     * Generated from protobuf field <code>int32 Size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->Size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Page = 5;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->Page;
    }

    /**
     * Generated from protobuf field <code>int32 Page = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->Page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

