<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QwUserPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.QwUserMessage</code>
 */
class QwUserMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string UserId = 1;</code>
     */
    private $UserId = '';
    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string Avatar = 3;</code>
     */
    private $Avatar = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserId
     *          
     *     @type string $Name
     *           微信号
     *     @type string $Avatar
     *          头像
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QwUserPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string UserId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserId = $var;

        return $this;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string Avatar = 3;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string Avatar = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

}

