<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemittanceTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.RemittanceTaskMessage</code>
 */
class RemittanceTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     *钱数，单位：分
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     */
    private $Money = 0;
    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 4;</code>
     */
    private $Passwd = '';
    /**
     * 留言
     *
     * Generated from protobuf field <code>string Memo = 5;</code>
     */
    private $Memo = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    private $TaskId = 0;
    /**
     *会话id（群聊id）
     *
     * Generated from protobuf field <code>string RoomId = 7;</code>
     */
    private $RoomId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $FriendId
     *          聊天好友微信唯一id
     *     @type int $Money
     *          钱数，单位：分
     *     @type string $Passwd
     *           密码，6位，纯数字
     *     @type string $Memo
     *           留言
     *     @type int|string $TaskId
     *          
     *     @type string $RoomId
     *          会话id（群聊id）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RemittanceTask::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     *钱数，单位：分
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     * @return int
     */
    public function getMoney()
    {
        return $this->Money;
    }

    /**
     *钱数，单位：分
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->Money = $var;

        return $this;
    }

    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 4;</code>
     * @return string
     */
    public function getPasswd()
    {
        return $this->Passwd;
    }

    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPasswd($var)
    {
        GPBUtil::checkString($var, True);
        $this->Passwd = $var;

        return $this;
    }

    /**
     * 留言
     *
     * Generated from protobuf field <code>string Memo = 5;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->Memo;
    }

    /**
     * 留言
     *
     * Generated from protobuf field <code>string Memo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->Memo = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     *会话id（群聊id）
     *
     * Generated from protobuf field <code>string RoomId = 7;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->RoomId;
    }

    /**
     *会话id（群聊id）
     *
     * Generated from protobuf field <code>string RoomId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoomId = $var;

        return $this;
    }

}

