<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestChatRoomInfoTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.RequestChatRoomInfoTaskMessage</code>
 */
class RequestChatRoomInfoTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>string ChatRoomId = 2;</code>
     */
    private $ChatRoomId = '';
    /**
     * Flag=1:推送成员信息（ChatRoomMembersNotice)
     *
     * Generated from protobuf field <code>int32 Flag = 3;</code>
     */
    private $Flag = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $ChatRoomId
     *     @type int $Flag
     *           Flag=1:推送成员信息（ChatRoomMembersNotice)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RequestChatRoomInfoTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ChatRoomId = 2;</code>
     * @return string
     */
    public function getChatRoomId()
    {
        return $this->ChatRoomId;
    }

    /**
     * Generated from protobuf field <code>string ChatRoomId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChatRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ChatRoomId = $var;

        return $this;
    }

    /**
     * Flag=1:推送成员信息（ChatRoomMembersNotice)
     *
     * Generated from protobuf field <code>int32 Flag = 3;</code>
     * @return int
     */
    public function getFlag()
    {
        return $this->Flag;
    }

    /**
     * Flag=1:推送成员信息（ChatRoomMembersNotice)
     *
     * Generated from protobuf field <code>int32 Flag = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->Flag = $var;

        return $this;
    }

}

