<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestTalkDetailTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.RequestTalkDetailTaskMessage</code>
 */
class RequestTalkDetailTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     */
    private $MsgId = 0;
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     */
    private $WeChatId = '';
    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     */
    private $FriendId = '';
    /**
     *微信设备上消息唯一id(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string MsgSvrId = 4;</code>
     */
    private $MsgSvrId = '';
    /**
     *图片或视频md5(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string Md5 = 5;</code>
     */
    private $Md5 = '';
    /**
     *获取原图（获取接收到的图片消息的原图时置true，其他false）
     *
     * Generated from protobuf field <code>bool GetOriginal = 6;</code>
     */
    private $GetOriginal = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $MsgId
     *          全局消息id
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $FriendId
     *          聊天好友微信唯一id
     *     @type string $MsgSvrId
     *          微信设备上消息唯一id(FriendTalkNotice中上传)
     *     @type string $Md5
     *          图片或视频md5(FriendTalkNotice中上传)
     *     @type bool $GetOriginal
     *          获取原图（获取接收到的图片消息的原图时置true，其他false）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RequestTalkDetailTask::initOnce();
        parent::__construct($data);
    }

    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     *微信设备上消息唯一id(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string MsgSvrId = 4;</code>
     * @return string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     *微信设备上消息唯一id(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string MsgSvrId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     *图片或视频md5(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string Md5 = 5;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->Md5;
    }

    /**
     *图片或视频md5(FriendTalkNotice中上传)
     *
     * Generated from protobuf field <code>string Md5 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->Md5 = $var;

        return $this;
    }

    /**
     *获取原图（获取接收到的图片消息的原图时置true，其他false）
     *
     * Generated from protobuf field <code>bool GetOriginal = 6;</code>
     * @return bool
     */
    public function getGetOriginal()
    {
        return $this->GetOriginal;
    }

    /**
     *获取原图（获取接收到的图片消息的原图时置true，其他false）
     *
     * Generated from protobuf field <code>bool GetOriginal = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetOriginal($var)
    {
        GPBUtil::checkBool($var);
        $this->GetOriginal = $var;

        return $this;
    }

}

