<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestTalkMsgTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.RequestTalkMsgTaskMessage</code>
 */
class RequestTalkMsgTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 2;</code>
     */
    private $MsgSvrId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          唯一Id
     *     @type int|string $MsgSvrId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RequestTalkMsgTask::initOnce();
        parent::__construct($data);
    }

    /**
     *唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 2;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgSvrId = $var;

        return $this;
    }

}

