<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RevokeMessageTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.RevokeMessageTaskMessage</code>
 */
class RevokeMessageTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     */
    private $MsgId = 0;
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     */
    private $WeChatId = '';
    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     */
    private $FriendId = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $MsgId
     *          消息的msgSvrId
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $FriendId
     *          聊天好友微信唯一id
     *     @type int|string $TaskId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RevokeMessageTask::initOnce();
        parent::__construct($data);
    }

    /**
     *消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     *消息的msgSvrId
     *
     * Generated from protobuf field <code>int64 MsgId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

