<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SearchBizContactTaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.SearchBizContactTaskResultNoticeMessage</code>
 */
class SearchBizContactTaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string KeyWord = 2;</code>
     */
    private $KeyWord = '';
    /**
     * 0：公众号；1：小程序
     *
     * Generated from protobuf field <code>int32 Type = 3;</code>
     */
    private $Type = 0;
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Items = 5;</code>
     */
    private $Items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $KeyWord
     *          搜索关键字
     *     @type int $Type
     *           0：公众号；1：小程序
     *     @type int|string $TaskId
     *          
     *     @type \Jubo\JuLiao\IM\Wx\Proto\BizContactMessage[]|\Google\Protobuf\Internal\RepeatedField $Items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SearchBizContactTaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string KeyWord = 2;</code>
     * @return string
     */
    public function getKeyWord()
    {
        return $this->KeyWord;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string KeyWord = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyWord($var)
    {
        GPBUtil::checkString($var, True);
        $this->KeyWord = $var;

        return $this;
    }

    /**
     * 0：公众号；1：小程序
     *
     * Generated from protobuf field <code>int32 Type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * 0：公众号；1：小程序
     *
     * Generated from protobuf field <code>int32 Type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Items = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Items = 5;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\BizContactMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\BizContactMessage::class);
        $this->Items = $arr;

        return $this;
    }

}

