<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendLuckyMoneyTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.SendLuckyMoneyTaskMessage</code>
 */
class SendLuckyMoneyTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     *钱数，单位：分，最多20000
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     */
    private $Money = 0;
    /**
     * 红包个数，缺省1个
     *
     * Generated from protobuf field <code>int32 Number = 4;</code>
     */
    private $Number = 0;
    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 5;</code>
     */
    private $Passwd = '';
    /**
     * 祝福语
     *
     * Generated from protobuf field <code>string Wish = 6;</code>
     */
    private $Wish = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $FriendId
     *          聊天好友微信唯一id
     *     @type int $Money
     *          钱数，单位：分，最多20000
     *     @type int $Number
     *           红包个数，缺省1个
     *     @type string $Passwd
     *           密码，6位，纯数字
     *     @type string $Wish
     *           祝福语
     *     @type int|string $TaskId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SendLuckyMoneyTask::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     *钱数，单位：分，最多20000
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     * @return int
     */
    public function getMoney()
    {
        return $this->Money;
    }

    /**
     *钱数，单位：分，最多20000
     *
     * Generated from protobuf field <code>int32 Money = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->Money = $var;

        return $this;
    }

    /**
     * 红包个数，缺省1个
     *
     * Generated from protobuf field <code>int32 Number = 4;</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->Number;
    }

    /**
     * 红包个数，缺省1个
     *
     * Generated from protobuf field <code>int32 Number = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->Number = $var;

        return $this;
    }

    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 5;</code>
     * @return string
     */
    public function getPasswd()
    {
        return $this->Passwd;
    }

    /**
     * 密码，6位，纯数字
     *
     * Generated from protobuf field <code>string Passwd = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPasswd($var)
    {
        GPBUtil::checkString($var, True);
        $this->Passwd = $var;

        return $this;
    }

    /**
     * 祝福语
     *
     * Generated from protobuf field <code>string Wish = 6;</code>
     * @return string
     */
    public function getWish()
    {
        return $this->Wish;
    }

    /**
     * 祝福语
     *
     * Generated from protobuf field <code>string Wish = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWish($var)
    {
        GPBUtil::checkString($var, True);
        $this->Wish = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

