<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetForbiddenWord.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.SetForbiddenWordMessage</code>
 */
class SetForbiddenWordMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    protected $WeChatId = '';
    /**
     * 需屏蔽的关键词列表
     *
     * Generated from protobuf field <code>repeated string KeyWord = 3;</code>
     */
    private $KeyWord;
    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord2 = 4;</code>
     */
    private $KeyWord2;
    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord3 = 5;</code>
     */
    private $KeyWord3;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $KeyWord
     *           需屏蔽的关键词列表
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $KeyWord2
     *           保留字段，未使用
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $KeyWord3
     *           保留字段，未使用
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SetForbiddenWord::initOnce();
        parent::__construct($data);
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 需屏蔽的关键词列表
     *
     * Generated from protobuf field <code>repeated string KeyWord = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyWord()
    {
        return $this->KeyWord;
    }

    /**
     * 需屏蔽的关键词列表
     *
     * Generated from protobuf field <code>repeated string KeyWord = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyWord($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->KeyWord = $arr;

        return $this;
    }

    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord2 = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyWord2()
    {
        return $this->KeyWord2;
    }

    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord2 = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyWord2($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->KeyWord2 = $arr;

        return $this;
    }

    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord3 = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyWord3()
    {
        return $this->KeyWord3;
    }

    /**
     * 保留字段，未使用
     *
     * Generated from protobuf field <code>repeated string KeyWord3 = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyWord3($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->KeyWord3 = $arr;

        return $this;
    }

}

