<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmsReadNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.SmsReadNoticeMessage</code>
 */
class SmsReadNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 手机设备号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     */
    private $IMEI = '';
    /**
     * 单条短信已读
     *
     * Generated from protobuf field <code>int32 SmsId = 3;</code>
     */
    private $SmsId = 0;
    /**
     * 整个会话已读
     *
     * Generated from protobuf field <code>int32 ThreadId = 4;</code>
     */
    private $ThreadId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           商家所属微信号
     *     @type string $IMEI
     *           手机设备号
     *     @type int $SmsId
     *           单条短信已读
     *     @type int $ThreadId
     *           整个会话已读
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SmsReadNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 商家所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 手机设备号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * 手机设备号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     * 单条短信已读
     *
     * Generated from protobuf field <code>int32 SmsId = 3;</code>
     * @return int
     */
    public function getSmsId()
    {
        return $this->SmsId;
    }

    /**
     * 单条短信已读
     *
     * Generated from protobuf field <code>int32 SmsId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSmsId($var)
    {
        GPBUtil::checkInt32($var);
        $this->SmsId = $var;

        return $this;
    }

    /**
     * 整个会话已读
     *
     * Generated from protobuf field <code>int32 ThreadId = 4;</code>
     * @return int
     */
    public function getThreadId()
    {
        return $this->ThreadId;
    }

    /**
     * 整个会话已读
     *
     * Generated from protobuf field <code>int32 ThreadId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setThreadId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ThreadId = $var;

        return $this;
    }

}

