<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SphMentionListNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.SphMentionListNoticeMessage</code>
 */
class SphMentionListNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    protected $WeChatId = '';
    /**
     * Generated from protobuf field <code>string SphUserName = 2;</code>
     */
    protected $SphUserName = '';
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage LikeList = 3;</code>
     */
    private $LikeList;
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage CommentList = 4;</code>
     */
    private $CommentList;
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage FollowList = 5;</code>
     */
    private $FollowList;
    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     */
    protected $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信号
     *     @type string $SphUserName
     *     @type \Jubo\JuLiao\IM\Wx\Proto\MentionMessage[]|\Google\Protobuf\Internal\RepeatedField $LikeList
     *     @type \Jubo\JuLiao\IM\Wx\Proto\MentionMessage[]|\Google\Protobuf\Internal\RepeatedField $CommentList
     *     @type \Jubo\JuLiao\IM\Wx\Proto\MentionMessage[]|\Google\Protobuf\Internal\RepeatedField $FollowList
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SphMentionListNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SphUserName = 2;</code>
     * @return string
     */
    public function getSphUserName()
    {
        return $this->SphUserName;
    }

    /**
     * Generated from protobuf field <code>string SphUserName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSphUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SphUserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage LikeList = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLikeList()
    {
        return $this->LikeList;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage LikeList = 3;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\MentionMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLikeList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\MentionMessage::class);
        $this->LikeList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage CommentList = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCommentList()
    {
        return $this->CommentList;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage CommentList = 4;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\MentionMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCommentList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\MentionMessage::class);
        $this->CommentList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage FollowList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFollowList()
    {
        return $this->FollowList;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.MentionMessage FollowList = 5;</code>
     * @param array<\Jubo\JuLiao\IM\Wx\Proto\MentionMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFollowList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\MentionMessage::class);
        $this->FollowList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

