<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomMembersNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.StrangerMessage</code>
 */
class StrangerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Wxid = 1;</code>
     */
    private $Wxid = '';
    /**
     * 微信别名
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     */
    private $Alias = '';
    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     */
    private $Nickname = '';
    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     */
    private $Avatar = '';
    /**
     * 联系人类型，判断是否为好友
     *
     * Generated from protobuf field <code>int32 Type = 5;</code>
     */
    private $Type = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 6;</code>
     */
    private $Gender = 0;
    /**
     *国家 (非必传)
     *
     * Generated from protobuf field <code>string Country = 7;</code>
     */
    private $Country = '';
    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 8;</code>
     */
    private $Province = '';
    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 9;</code>
     */
    private $City = '';
    /**
     * 机主的备注
     *
     * Generated from protobuf field <code>string Memo = 10;</code>
     */
    private $Memo = '';
    /**
     *签名
     *
     * Generated from protobuf field <code>string Signature = 11;</code>
     */
    private $Signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Wxid
     *           微信号
     *     @type string $Alias
     *           微信别名
     *     @type string $Nickname
     *           好友的微信昵称
     *     @type string $Avatar
     *          微信头像 
     *     @type int $Type
     *           联系人类型，判断是否为好友
     *     @type int $Gender
     *          性别
     *     @type string $Country
     *          国家 (非必传)
     *     @type string $Province
     *          省份
     *     @type string $City
     *          城市
     *     @type string $Memo
     *           机主的备注
     *     @type string $Signature
     *          签名
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChatRoomMembersNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Wxid = 1;</code>
     * @return string
     */
    public function getWxid()
    {
        return $this->Wxid;
    }

    /**
     * 微信号
     *
     * Generated from protobuf field <code>string Wxid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWxid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Wxid = $var;

        return $this;
    }

    /**
     * 微信别名
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->Alias;
    }

    /**
     * 微信别名
     *
     * Generated from protobuf field <code>string Alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->Alias = $var;

        return $this;
    }

    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->Nickname;
    }

    /**
     * 好友的微信昵称
     *
     * Generated from protobuf field <code>string Nickname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->Nickname = $var;

        return $this;
    }

    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     *微信头像 
     *
     * Generated from protobuf field <code>string Avatar = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * 联系人类型，判断是否为好友
     *
     * Generated from protobuf field <code>int32 Type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * 联系人类型，判断是否为好友
     *
     * Generated from protobuf field <code>int32 Type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 6;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->Gender;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumGender::class);
        $this->Gender = $var;

        return $this;
    }

    /**
     *国家 (非必传)
     *
     * Generated from protobuf field <code>string Country = 7;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     *国家 (非必传)
     *
     * Generated from protobuf field <code>string Country = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->Country = $var;

        return $this;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 8;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->Province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->Province = $var;

        return $this;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 9;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     * 机主的备注
     *
     * Generated from protobuf field <code>string Memo = 10;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->Memo;
    }

    /**
     * 机主的备注
     *
     * Generated from protobuf field <code>string Memo = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->Memo = $var;

        return $this;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string Signature = 11;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->Signature;
    }

    /**
     *签名
     *
     * Generated from protobuf field <code>string Signature = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->Signature = $var;

        return $this;
    }

}

