<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeLuckyMoneyTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TakeLuckyMoneyTaskMessage</code>
 */
class TakeLuckyMoneyTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     */
    private $MsgSvrId = 0;
    /**
     * 消息内容中的Key
     *
     * Generated from protobuf field <code>string MsgKey = 4;</code>
     */
    private $MsgKey = '';
    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信唯一Id
     *     @type string $FriendId
     *          聊天好友微信唯一id
     *     @type int|string $MsgSvrId
     *          全局消息id
     *     @type string $MsgKey
     *           消息内容中的Key
     *     @type int|string $TaskId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TakeLuckyMoneyTask::initOnce();
        parent::__construct($data);
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信唯一Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     *聊天好友微信唯一id
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @return int|string
     */
    public function getMsgSvrId()
    {
        return $this->MsgSvrId;
    }

    /**
     *全局消息id
     *
     * Generated from protobuf field <code>int64 MsgSvrId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgSvrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgSvrId = $var;

        return $this;
    }

    /**
     * 消息内容中的Key
     *
     * Generated from protobuf field <code>string MsgKey = 4;</code>
     * @return string
     */
    public function getMsgKey()
    {
        return $this->MsgKey;
    }

    /**
     * 消息内容中的Key
     *
     * Generated from protobuf field <code>string MsgKey = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->MsgKey = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>int64 TaskId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

