<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TalkToFriendTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TalkToFriendTaskMessage</code>
 */
class TalkToFriendTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 发送给那个好友
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';
    /**
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     */
    private $ContentType = 0;
    /**
     * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     *
     * Generated from protobuf field <code>bytes Content = 4;</code>
     */
    private $Content = '';
    /**
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     *
     * Generated from protobuf field <code>string Remark = 8;</code>
     */
    private $Remark = '';
    /**
     * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     *
     * Generated from protobuf field <code>int64 MsgId = 9;</code>
     */
    private $MsgId = 0;
    /**
     *立即发送（用于群发消息时优先发送聊天消息）
     *
     * Generated from protobuf field <code>bool Immediate = 10;</code>
     */
    private $Immediate = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信号
     *     @type string $FriendId
     *           发送给那个好友
     *     @type int $ContentType
     *           发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     *     @type string $Content
     *           发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     *     @type string $Remark
     *           其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     *     @type int|string $MsgId
     *           发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     *     @type bool $Immediate
     *          立即发送（用于群发消息时优先发送聊天消息）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TalkToFriendTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 发送给那个好友
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * 发送给那个好友
     *
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

    /**
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumContentType ContentType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumContentType::class);
        $this->ContentType = $var;

        return $this;
    }

    /**
     * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     *
     * Generated from protobuf field <code>bytes Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     *
     * Generated from protobuf field <code>bytes Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     *
     * Generated from protobuf field <code>string Remark = 8;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     *
     * Generated from protobuf field <code>string Remark = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

    /**
     * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     *
     * Generated from protobuf field <code>int64 MsgId = 9;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     *
     * Generated from protobuf field <code>int64 MsgId = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     *立即发送（用于群发消息时优先发送聊天消息）
     *
     * Generated from protobuf field <code>bool Immediate = 10;</code>
     * @return bool
     */
    public function getImmediate()
    {
        return $this->Immediate;
    }

    /**
     *立即发送（用于群发消息时优先发送聊天消息）
     *
     * Generated from protobuf field <code>bool Immediate = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setImmediate($var)
    {
        GPBUtil::checkBool($var);
        $this->Immediate = $var;

        return $this;
    }

}

