<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskResultNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TaskResultNoticeMessage</code>
 */
class TaskResultNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     */
    private $Success = false;
    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     */
    private $Code = 0;
    /**
     * 错误内容描述 获取 成功时附带的结果内容
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     */
    private $ErrMsg = '';
    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    private $TaskId = 0;
    /**
     *原来执行的任务的类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     */
    private $TaskType = 0;
    /**
     * 执行的微信
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     */
    private $WeChatId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Success
     *           是否成功
     *     @type int $Code
     *           错误码 Success = true 忽略
     *     @type string $ErrMsg
     *           错误内容描述 获取 成功时附带的结果内容
     *     @type int|string $TaskId
     *           业务的id,通用的。
     *     @type int $TaskType
     *          原来执行的任务的类型
     *     @type string $WeChatId
     *           执行的微信
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TaskResultNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->Success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool Success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->Success = $var;

        return $this;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 错误码 Success = true 忽略
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumErrorCode Code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumErrorCode::class);
        $this->Code = $var;

        return $this;
    }

    /**
     * 错误内容描述 获取 成功时附带的结果内容
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->ErrMsg;
    }

    /**
     * 错误内容描述 获取 成功时附带的结果内容
     *
     * Generated from protobuf field <code>string ErrMsg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMsg = $var;

        return $this;
    }

    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * 业务的id,通用的。
     *
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     *原来执行的任务的类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     * @return int
     */
    public function getTaskType()
    {
        return $this->TaskType;
    }

    /**
     *原来执行的任务的类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumMsgType TaskType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTaskType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumMsgType::class);
        $this->TaskType = $var;

        return $this;
    }

    /**
     * 执行的微信
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 执行的微信
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

}

