<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerConfigPush.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TriggerConfigPushMessage</code>
 */
class TriggerConfigPushMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 设备号
     *
     * Generated from protobuf field <code>string IMEI = 1;</code>
     */
    private $IMEI = '';
    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     */
    private $WeChatId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $IMEI
     *           设备号
     *     @type string $WeChatId
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TriggerConfigPush::initOnce();
        parent::__construct($data);
    }

    /**
     * 设备号
     *
     * Generated from protobuf field <code>string IMEI = 1;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * 设备号
     *
     * Generated from protobuf field <code>string IMEI = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string WeChatId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

}

