<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerUnreadPushTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TriggerUnreadPushTaskMessage</code>
 */
class TriggerUnreadPushTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     */
    private $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信号
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TriggerUnreadPushTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

