<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerChatMsgIdsPushTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TriggerChatMsgIdsPushTaskMessage</code>
 */
class TriggerChatMsgIdsPushTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 开始同步的消息时间，UTC毫秒，最多一天
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     */
    private $StartTime = 0;
    /**
     * 结束同步的消息时间，UTC毫秒,一般为当前时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     */
    private $EndTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信号
     *     @type int|string $StartTime
     *           开始同步的消息时间，UTC毫秒，最多一天
     *     @type int|string $EndTime
     *           结束同步的消息时间，UTC毫秒,一般为当前时间
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TriggerChatMsgIdsPushTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信号
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 开始同步的消息时间，UTC毫秒，最多一天
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 开始同步的消息时间，UTC毫秒，最多一天
     *
     * Generated from protobuf field <code>int64 StartTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 结束同步的消息时间，UTC毫秒,一般为当前时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 结束同步的消息时间，UTC毫秒,一般为当前时间
     *
     * Generated from protobuf field <code>int64 EndTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

}

