<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerCirclePushTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.TriggerCirclePushTaskMessage</code>
 */
class TriggerCirclePushTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    protected $WeChatId = '';
    /**
     * 起始时间 选其一 单位 秒
     *
     * Generated from protobuf field <code>int64 StartTime = 2;</code>
     */
    protected $StartTime = 0;
    /**
     * 废弃，准备删除
     *
     * Generated from protobuf field <code>repeated int64 CircleIds = 3;</code>
     */
    private $CircleIds;
    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     */
    protected $TaskId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           所属微信
     *     @type int|string $StartTime
     *           起始时间 选其一 单位 秒
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $CircleIds
     *           废弃，准备删除
     *     @type int|string $TaskId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TriggerCirclePushTask::initOnce();
        parent::__construct($data);
    }

    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 所属微信
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 起始时间 选其一 单位 秒
     *
     * Generated from protobuf field <code>int64 StartTime = 2;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 起始时间 选其一 单位 秒
     *
     * Generated from protobuf field <code>int64 StartTime = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 废弃，准备删除
     *
     * Generated from protobuf field <code>repeated int64 CircleIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCircleIds()
    {
        return $this->CircleIds;
    }

    /**
     * 废弃，准备删除
     *
     * Generated from protobuf field <code>repeated int64 CircleIds = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCircleIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->CircleIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int64 TaskId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

}

