<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnreadListPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.UnreadMessage</code>
 */
class UnreadMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 会话ID
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 2;</code>
     */
    private $UnreadCnt = 0;
    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 3;</code>
     */
    private $UpdateTime = 0;
    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 4;</code>
     */
    private $IsSilent = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserName
     *           会话ID
     *     @type int $UnreadCnt
     *           未读消息条数
     *     @type int|string $UpdateTime
     *           最后消息的时间
     *     @type bool $IsSilent
     *           是否消息免打扰
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UnreadListPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 会话ID
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * 会话ID
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 2;</code>
     * @return int
     */
    public function getUnreadCnt()
    {
        return $this->UnreadCnt;
    }

    /**
     * 未读消息条数
     *
     * Generated from protobuf field <code>int32 UnreadCnt = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnreadCnt($var)
    {
        GPBUtil::checkInt32($var);
        $this->UnreadCnt = $var;

        return $this;
    }

    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 3;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->UpdateTime;
    }

    /**
     * 最后消息的时间
     *
     * Generated from protobuf field <code>int64 UpdateTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->UpdateTime = $var;

        return $this;
    }

    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 4;</code>
     * @return bool
     */
    public function getIsSilent()
    {
        return $this->IsSilent;
    }

    /**
     * 是否消息免打扰
     *
     * Generated from protobuf field <code>bool IsSilent = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSilent($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSilent = $var;

        return $this;
    }

}

