<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpgradeDeviceAppNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.UpgradeDeviceAppNoticeMessage</code>
 */
class UpgradeDeviceAppNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * Generated from protobuf field <code>string IMEI = 2;</code>
     */
    private $IMEI = '';
    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.DeviceAppUpgradeMessage AppInfos = 3;</code>
     */
    private $AppInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *     @type string $IMEI
     *     @type \Jubo\JuLiao\IM\Wx\Proto\DeviceAppUpgradeMessage[]|\Google\Protobuf\Internal\RepeatedField $AppInfos
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UpgradeDeviceAppNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.DeviceAppUpgradeMessage AppInfos = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppInfos()
    {
        return $this->AppInfos;
    }

    /**
     * Generated from protobuf field <code>repeated .Jubo.JuLiao.IM.Wx.Proto.DeviceAppUpgradeMessage AppInfos = 3;</code>
     * @param \Jubo\JuLiao\IM\Wx\Proto\DeviceAppUpgradeMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jubo\JuLiao\IM\Wx\Proto\DeviceAppUpgradeMessage::class);
        $this->AppInfos = $arr;

        return $this;
    }

}

