<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatGroupSendTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.WeChatGroupSendTaskMessage</code>
 */
class WeChatGroupSendTaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *任务id
     *
     * Generated from protobuf field <code>int64 TaskId = 1;</code>
     */
    private $TaskId = 0;
    /**
     *目标人群id列表
     *
     * Generated from protobuf field <code>repeated string FriendIds = 3;</code>
     */
    private $FriendIds;
    /**
     *内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.WeChatGroupSendTaskMessage.EnumGroupMsgContentType ContentType = 4;</code>
     */
    private $ContentType = 0;
    /**
     *文字内容 或 图片,视频，语音url
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     */
    private $Content = '';
    /**
     *微信号id
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     */
    private $WeChatId = '';
    /**
     * 视频，语音的时长
     *
     * Generated from protobuf field <code>int32 Duration = 7;</code>
     */
    private $Duration = 0;
    /**
     * 发送原图
     *
     * Generated from protobuf field <code>bool Original = 8;</code>
     */
    private $Original = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $TaskId
     *          任务id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $FriendIds
     *          目标人群id列表
     *     @type int $ContentType
     *          内容类型
     *     @type string $Content
     *          文字内容 或 图片,视频，语音url
     *     @type string $WeChatId
     *          微信号id
     *     @type int $Duration
     *           视频，语音的时长
     *     @type bool $Original
     *           发送原图
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WeChatGroupSendTask::initOnce();
        parent::__construct($data);
    }

    /**
     *任务id
     *
     * Generated from protobuf field <code>int64 TaskId = 1;</code>
     * @return int|string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *任务id
     *
     * Generated from protobuf field <code>int64 TaskId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TaskId = $var;

        return $this;
    }

    /**
     *目标人群id列表
     *
     * Generated from protobuf field <code>repeated string FriendIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriendIds()
    {
        return $this->FriendIds;
    }

    /**
     *目标人群id列表
     *
     * Generated from protobuf field <code>repeated string FriendIds = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriendIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FriendIds = $arr;

        return $this;
    }

    /**
     *内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.WeChatGroupSendTaskMessage.EnumGroupMsgContentType ContentType = 4;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->ContentType;
    }

    /**
     *内容类型
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.WeChatGroupSendTaskMessage.EnumGroupMsgContentType ContentType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\WeChatGroupSendTaskMessage_EnumGroupMsgContentType::class);
        $this->ContentType = $var;

        return $this;
    }

    /**
     *文字内容 或 图片,视频，语音url
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     *文字内容 或 图片,视频，语音url
     *
     * Generated from protobuf field <code>string Content = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     *微信号id
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信号id
     *
     * Generated from protobuf field <code>string WeChatId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 视频，语音的时长
     *
     * Generated from protobuf field <code>int32 Duration = 7;</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->Duration;
    }

    /**
     * 视频，语音的时长
     *
     * Generated from protobuf field <code>int32 Duration = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->Duration = $var;

        return $this;
    }

    /**
     * 发送原图
     *
     * Generated from protobuf field <code>bool Original = 8;</code>
     * @return bool
     */
    public function getOriginal()
    {
        return $this->Original;
    }

    /**
     * 发送原图
     *
     * Generated from protobuf field <code>bool Original = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setOriginal($var)
    {
        GPBUtil::checkBool($var);
        $this->Original = $var;

        return $this;
    }

}

