<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatOnlineNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.WeChatOnlineNoticeMessage</code>
 */
class WeChatOnlineNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     *微信号（如果用户设置了微信号）
     *
     * Generated from protobuf field <code>string WeChatNo = 2;</code>
     */
    private $WeChatNo = '';
    /**
     *微信昵称
     *
     * Generated from protobuf field <code>string WeChatNick = 3;</code>
     */
    private $WeChatNick = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 4;</code>
     */
    private $Gender = 0;
    /**
     *国家
     *
     * Generated from protobuf field <code>string Country = 5;</code>
     */
    private $Country = '';
    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 6;</code>
     */
    private $Province = '';
    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 7;</code>
     */
    private $City = '';
    /**
     *微信头像
     *
     * Generated from protobuf field <code>string Avatar = 8;</code>
     */
    private $Avatar = '';
    /**
     * imei号
     *
     * Generated from protobuf field <code>string IMEI = 9;</code>
     */
    private $IMEI = '';
    /**
     *
     *
     * Generated from protobuf field <code>string Phone = 10;</code>
     */
    private $Phone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *          微信内部全局唯一识别码
     *     @type string $WeChatNo
     *          微信号（如果用户设置了微信号）
     *     @type string $WeChatNick
     *          微信昵称
     *     @type int $Gender
     *          性别
     *     @type string $Country
     *          国家
     *     @type string $Province
     *          省份
     *     @type string $City
     *          城市
     *     @type string $Avatar
     *          微信头像
     *     @type string $IMEI
     *           imei号
     *     @type string $Phone
     *          
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WeChatOnlineNotice::initOnce();
        parent::__construct($data);
    }

    /**
     *微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     *微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     *微信号（如果用户设置了微信号）
     *
     * Generated from protobuf field <code>string WeChatNo = 2;</code>
     * @return string
     */
    public function getWeChatNo()
    {
        return $this->WeChatNo;
    }

    /**
     *微信号（如果用户设置了微信号）
     *
     * Generated from protobuf field <code>string WeChatNo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatNo = $var;

        return $this;
    }

    /**
     *微信昵称
     *
     * Generated from protobuf field <code>string WeChatNick = 3;</code>
     * @return string
     */
    public function getWeChatNick()
    {
        return $this->WeChatNick;
    }

    /**
     *微信昵称
     *
     * Generated from protobuf field <code>string WeChatNick = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatNick($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatNick = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 4;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->Gender;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Jubo\JuLiao\IM\Wx\Proto\EnumGender::class);
        $this->Gender = $var;

        return $this;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string Country = 5;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     *国家
     *
     * Generated from protobuf field <code>string Country = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->Country = $var;

        return $this;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 6;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->Province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->Province = $var;

        return $this;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 7;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     *城市
     *
     * Generated from protobuf field <code>string City = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     *微信头像
     *
     * Generated from protobuf field <code>string Avatar = 8;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     *微信头像
     *
     * Generated from protobuf field <code>string Avatar = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->Avatar = $var;

        return $this;
    }

    /**
     * imei号
     *
     * Generated from protobuf field <code>string IMEI = 9;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * imei号
     *
     * Generated from protobuf field <code>string IMEI = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Phone = 10;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->Phone;
    }

    /**
     *
     *
     * Generated from protobuf field <code>string Phone = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->Phone = $var;

        return $this;
    }

}

