<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatLoginNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

if (false) {
    /**
     * This class is deprecated. Use Jubo\JuLiao\IM\Wx\Proto\WeChatLoginNoticeMessage\WeChatLoginMessage instead.
     * @deprecated
     */
    class WeChatLoginNoticeMessage_WeChatLoginMessage {}
}
class_exists(WeChatLoginNoticeMessage\WeChatLoginMessage::class);
@trigger_error('Jubo\JuLiao\IM\Wx\Proto\WeChatLoginNoticeMessage_WeChatLoginMessage is deprecated and will be removed in the next major release. Use Jubo\JuLiao\IM\Wx\Proto\WeChatLoginNoticeMessage\WeChatLoginMessage instead', E_USER_DEPRECATED);

