<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatOfflineNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.WeChatOfflineNoticeMessage</code>
 */
class WeChatOfflineNoticeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 设备唯一号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     */
    private $IMEI = '';
    /**
     * Generated from protobuf field <code>int32 Reason = 3;</code>
     */
    private $Reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           微信内部全局唯一识别码
     *     @type string $IMEI
     *           设备唯一号
     *     @type int $Reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WeChatOfflineNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 微信内部全局唯一识别码
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 设备唯一号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @return string
     */
    public function getIMEI()
    {
        return $this->IMEI;
    }

    /**
     * 设备唯一号
     *
     * Generated from protobuf field <code>string IMEI = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIMEI($var)
    {
        GPBUtil::checkString($var, True);
        $this->IMEI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Reason = 3;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->Reason;
    }

    /**
     * Generated from protobuf field <code>int32 Reason = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkInt32($var);
        $this->Reason = $var;

        return $this;
    }

}

