<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatLoginNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto\WeChatLoginNoticeMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeMessage.WeChatLoginMessage</code>
 */
class WeChatLoginMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 微信Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     */
    private $WeChatId = '';
    /**
     * 是否登陆 false 代表退出
     *
     * Generated from protobuf field <code>bool IsLogin = 2;</code>
     */
    private $IsLogin = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $WeChatId
     *           微信Id
     *     @type bool $IsLogin
     *           是否登陆 false 代表退出
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WeChatLoginNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 微信Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @return string
     */
    public function getWeChatId()
    {
        return $this->WeChatId;
    }

    /**
     * 微信Id
     *
     * Generated from protobuf field <code>string WeChatId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->WeChatId = $var;

        return $this;
    }

    /**
     * 是否登陆 false 代表退出
     *
     * Generated from protobuf field <code>bool IsLogin = 2;</code>
     * @return bool
     */
    public function getIsLogin()
    {
        return $this->IsLogin;
    }

    /**
     * 是否登陆 false 代表退出
     *
     * Generated from protobuf field <code>bool IsLogin = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLogin($var)
    {
        GPBUtil::checkBool($var);
        $this->IsLogin = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WeChatLoginMessage::class, \Jubo\JuLiao\IM\Wx\Proto\WeChatLoginNoticeMessage_WeChatLoginMessage::class);

