<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddFriendNameCardTask.proto

namespace GPBMetadata;

class AddFriendNameCardTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a1b416464467269656e644e616d65436172645461736b2e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22730a" .
            "1c416464467269656e644e616d65436172645461736b4d65737361676512" .
            "100a08576543686174496418012001280912100a084d7367537672496418" .
            "0320012803120f0a074d657373616765180420012809120e0a0652656d61" .
            "726b180520012809120e0a065461736b4964180620012803620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

