<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddFriendFromPhonebookTask.proto

namespace GPBMetadata;

class AddFriendFromPhonebookTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9010a20416464467269656e6446726f6d50686f6e65626f6f6b546173" .
            "6b2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f" .
            "746f2283010a21416464467269656e6446726f6d50686f6e65626f6f6b54" .
            "61736b4d65737361676512100a085765436861744964180120012809120d" .
            "0a05436f756e74180220012805120d0a055265736574180320012808120f" .
            "0a074d657373616765180420012809120e0a065461736b49641805200128" .
            "03120d0a05496e646578180620012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

