<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddFriendWithSceneTask.proto

namespace GPBMetadata;

class AddFriendWithSceneTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad2010a1c416464467269656e64576974685363656e655461736b2e7072" .
            "6f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f2290" .
            "010a1d416464467269656e64576974685363656e655461736b4d65737361" .
            "676512100a085765436861744964180120012809120e0a06467269656e64" .
            "180220012809120f0a074d657373616765180320012809120d0a05536365" .
            "6e65180420012805120e0a0652656d61726b180520012809120e0a065461" .
            "736b4964180620012803120d0a054c6162656c180720012809620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

