<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgreeJoinChatRoomTask.proto

namespace GPBMetadata;

class AgreeJoinChatRoomTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a1b41677265654a6f696e43686174526f6f6d5461736b2e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22760a" .
            "1c41677265654a6f696e43686174526f6f6d5461736b4d65737361676512" .
            "100a085765436861744964180120012809120e0a0654616c6b6572180220" .
            "01280912100a084d7367537672496418032001280312120a0a4d7367436f" .
            "6e74656e74180420012809120e0a067461736b4964180520012803620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

