<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CDNDownloadResultNotice.proto

namespace GPBMetadata;

class CDNDownloadResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a1d43444e446f776e6c6f6164526573756c744e6f746963652e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22" .
            "82010a1e43444e446f776e6c6f6164526573756c744e6f746963654d6573" .
            "7361676512100a085765436861744964180120012809120f0a0753756363" .
            "657373180220012808120e0a064572724d7367180320012809120e0a0646" .
            "696c65496418042001280912100a084d7367537672496418052001280312" .
            "0b0a0355726c180620012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

