<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatMsgFilePushNotice.proto

namespace GPBMetadata;

class ChatMsgFilePushNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a1b436861744d736746696c65507573684e6f746963652e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f228301" .
            "0a1c436861744d736746696c65507573684e6f746963654d657373616765" .
            "12100a08576543686174496418012001280912100a084d73675376724964" .
            "180220012803120f0a074d736754797065180320012805120b0a0355726c" .
            "18042001280912100a0846696c6553697a65180520012803120f0a075375" .
            "6254797065180620012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

