<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatMsgIdsPushNotice.proto

namespace GPBMetadata;

class ChatMsgIdsPushNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a1a436861744d7367496473507573684e6f746963652e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22600a1b" .
            "436861744d7367496473507573684e6f746963654d65737361676512100a" .
            "08576543686174496418012001280912110a09537461727454696d651802" .
            "20012803120f0a07456e6454696d65180320012803120b0a034964731804" .
            "20032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

