<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomMembersNotice.proto

namespace GPBMetadata;

class ChatRoomMembersNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93030a1b43686174526f6f6d4d656d626572734e6f746963652e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22e501" .
            "0a0f537472616e6765724d657373616765120c0a04577869641801200128" .
            "09120d0a05416c69617318022001280912100a084e69636b6e616d651803" .
            "20012809120e0a06417661746172180420012809120c0a04547970651805" .
            "2001280512330a0647656e64657218062001280e32232e4a75626f2e4a75" .
            "4c69616f2e494d2e57782e50726f746f2e456e756d47656e646572120f0a" .
            "07436f756e74727918072001280912100a0850726f76696e636518082001" .
            "2809120c0a0443697479180920012809120c0a044d656d6f180a20012809" .
            "12110a095369676e6174757265180b20012809226b0a1c43686174526f6f" .
            "6d4d656d626572734e6f746963654d65737361676512100a085765436861" .
            "74496418012001280912390a074d656d6265727318032003280b32282e4a" .
            "75626f2e4a754c69616f2e494d2e57782e50726f746f2e537472616e6765" .
            "724d657373616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

