<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomChangedNotice.proto

namespace GPBMetadata;

class ChatRoomChangedNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8030a1b43686174526f6f6d4368616e6765644e6f746963652e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f228e01" .
            "0a1c43686174526f6f6d4368616e6765644e6f746963654d657373616765" .
            "12100a08576543686174496418012001280912100a08557365724e616d65" .
            "18022001280912390a045768617418032001280e322b2e4a75626f2e4a75" .
            "4c69616f2e494d2e57782e50726f746f2e456e756d43686174526f6f6d43" .
            "68616e6765120f0a07436f6e74656e741804200128092ad6010a12456e75" .
            "6d43686174526f6f6d4368616e676512150a114368616e67655f4d656d62" .
            "65724c697374100012170a134368616e67655f5075626c69634e6f746963" .
            "65100112130a0f4368616e67655f4e69636b4e616d65100212130a0f4368" .
            "616e67655f53686f774e616d65100312150a114368616e67655f4d795368" .
            "6f774e616d65100412100a0c4368616e67655f4f776e6572100512110a0d" .
            "4368616e67655f417661746172100612140a104368616e67655f4d656d62" .
            "6572416464100712140a104368616e67655f4d656d62657244656c100862" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

