<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomDelNotice.proto

namespace GPBMetadata;

class ChatRoomDelNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a780a1743686174526f6f6d44656c4e6f746963652e70726f746f12174a" .
            "75626f2e4a754c69616f2e494d2e57782e50726f746f223c0a1843686174" .
            "526f6f6d44656c4e6f746963654d65737361676512100a08576543686174" .
            "4964180120012809120e0a06526f6f6d4964180220012809620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

