<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomAddNotice.proto

namespace GPBMetadata;

class ChatRoomAddNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChatRoomPushNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a1743686174526f6f6d4164644e6f746963652e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f22680a18436861" .
            "74526f6f6d4164644e6f746963654d65737361676512100a085765436861" .
            "744964180120012809123a0a0843686174526f6f6d18022001280b32282e" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e43686174526f" .
            "6f6d4d657373616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

