<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleCommentDeleteTask.proto

namespace GPBMetadata;

class CircleCommentDeleteTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a1d436972636c65436f6d6d656e7444656c6574655461736b2e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22" .
            "7c0a1e436972636c65436f6d6d656e7444656c6574655461736b4d657373" .
            "61676512100a08576543686174496418012001280912100a08436972636c" .
            "65496418022001280312110a09436f6d6d656e7449641803200128031213" .
            "0a0b5075626c69736854696d65180420012803120e0a065461736b496418" .
            "0520012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

