<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleMsgPushNotice.proto

namespace GPBMetadata;

class CircleMsgPushNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CircleNewPublishNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a19436972636c654d7367507573684e6f746963652e70726f746f" .
            "12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22ba010a1a" .
            "436972636c654d7367507573684e6f746963654d65737361676512100a08" .
            "5765436861744964180120012809123f0a08436f6d6d656e747318022003" .
            "280b322d2e4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e43" .
            "6972636c65436f6d6d656e744d65737361676512390a054c696b65731803" .
            "2003280b322a2e4a75626f2e4a754c69616f2e494d2e57782e50726f746f" .
            "2e436972636c654c696b654d657373616765120e0a065461736b49641804" .
            "20012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

