<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleMsgReadTask.proto

namespace GPBMetadata;

class CircleMsgReadTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a17436972636c654d7367526561645461736b2e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f22510a18436972" .
            "636c654d7367526561645461736b4d65737361676512100a085765436861" .
            "74496418012001280912100a08436972636c65496418022001280312110a" .
            "09436f6d6d656e744964180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

