<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleCommentNotice.proto

namespace GPBMetadata;

class CircleCommentNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CircleNewPublishNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a19436972636c65436f6d6d656e744e6f746963652e70726f746f" .
            "12174a75626f2e4a754c69616f2e494d2e57782e50726f746f2292010a1a" .
            "436972636c65436f6d6d656e744e6f746963654d65737361676512100a08" .
            "576543686174496418012001280912100a08436972636c65496418022001" .
            "280312100a08497344656c657465180320012808123e0a07436f6d6d656e" .
            "7418042001280b322d2e4a75626f2e4a754c69616f2e494d2e57782e5072" .
            "6f746f2e436972636c65436f6d6d656e744d657373616765620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

