<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleDetailNotice.proto

namespace GPBMetadata;

class CircleDetailNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CircleNewPublishNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a18436972636c6544657461696c4e6f746963652e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f22700a194369" .
            "72636c6544657461696c4e6f746963654d65737361676512100a08576543" .
            "686174496418012001280912410a06436972636c6518022001280b32312e" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e436972636c65" .
            "496e666f726d6174696f6e4d657373616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

