<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleMsgClearTask.proto

namespace GPBMetadata;

class CircleMsgClearTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a18436972636c654d7367436c6561725461736b2e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f22620a194369" .
            "72636c654d7367436c6561725461736b4d65737361676512100a08576543" .
            "686174496418012001280912100a08436972636c65496418022001280312" .
            "110a09436f6d6d656e744964180320012805120e0a064973526561641804" .
            "20012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

