<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactSetLabelTask.proto

namespace GPBMetadata;

class ContactSetLabelTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0010a19436f6e746163745365744c6162656c5461736b2e70726f746f" .
            "12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22620a1a43" .
            "6f6e746163745365744c6162656c5461736b4d65737361676512100a0857" .
            "6543686174496418012001280912100a08467269656e6449641802200128" .
            "0912100a084c6162656c496473180320032805120e0a067461736b496418" .
            "0420012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

