<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactInfoNotice.proto

namespace GPBMetadata;

class ContactInfoNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChatRoomMembersNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5010a17436f6e74616374496e666f4e6f746963652e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f2298010a18436f" .
            "6e74616374496e666f4e6f746963654d65737361676512100a0857654368" .
            "6174496418012001280912390a07436f6e7461637418022001280b32282e" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e537472616e67" .
            "65724d657373616765120e0a065461736b4964180320012803120f0a0753" .
            "756363657373180420012808120e0a064572724d73671805200128096206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

