<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactLabelTask.proto

namespace GPBMetadata;

class ContactLabelTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a16436f6e746163744c6162656c5461736b2e70726f746f12174a" .
            "75626f2e4a754c69616f2e494d2e57782e50726f746f2281010a17436f6e" .
            "746163744c6162656c5461736b4d65737361676512100a08576543686174" .
            "496418012001280912110a094c6162656c4e616d65180220012809120f0a" .
            "074c6162656c4964180320012805120f0a074164644c6973741804200128" .
            "09120f0a0744656c4c697374180520012809120e0a067461736b49641806" .
            "20012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

