<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeleteSNSNewsTask.proto

namespace GPBMetadata;

class DeleteSNSNewsTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a1744656c657465534e534e6577735461736b2e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f224e0a1844656c" .
            "657465534e534e6577735461736b4d65737361676512100a085765436861" .
            "74496418012001280912100a08436972636c654964180220012803120e0a" .
            "065461736b4964180320012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

