<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeviceAuthRsp.proto

namespace GPBMetadata;

class DeviceAuthRsp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb020a13446576696365417574685273702e70726f746f12174a75626f" .
            "2e4a754c69616f2e494d2e57782e50726f746f22a2020a14446576696365" .
            "417574685273704d65737361676512130a0b416363657373546f6b656e18" .
            "012001280912490a05457874726118022001280b323a2e4a75626f2e4a75" .
            "4c69616f2e494d2e57782e50726f746f2e44657669636541757468527370" .
            "4d6573736167652e45787472614d6573736167651aa9010a0c4578747261" .
            "4d65737361676512120a0a537570706c6965724964180120012803120f0a" .
            "07556e696f6e4964180220012803123d0a0b4163636f756e745479706518" .
            "032001280e32282e4a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f2e456e756d4163636f756e745479706512140a0c537570706c6965724e" .
            "616d6518042001280912100a084e69636b4e616d65180520012809120d0a" .
            "05546f6b656e180620012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

