<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessageByContentTask.proto

namespace GPBMetadata;

class ForwardMessageByContentTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a21466f72776172644d6573736167654279436f6e74656e745461" .
            "736b2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e5072" .
            "6f746f229c010a22466f72776172644d6573736167654279436f6e74656e" .
            "745461736b4d65737361676512100a085765436861744964180120012809" .
            "12110a09467269656e6449647318022001280912100a084d736753767249" .
            "64180320012803120f0a074d736754797065180420012805120f0a07436f" .
            "6e74656e74180520012809120e0a065461736b4964180620012803120d0a" .
            "055468756d62180720012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

