<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessageTask.proto

namespace GPBMetadata;

class ForwardMessageTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a18466f72776172644d6573736167655461736b2e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f2282010a1946" .
            "6f72776172644d6573736167655461736b4d65737361676512100a084d73" .
            "67537276496418012001280312100a085765436861744964180220012809" .
            "12110a09467269656e64496473180320012809120e0a064578744d736718" .
            "0420012809120e0a0654616c6b6572180520012809120e0a065461736b49" .
            "64180620012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

