<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendPushNotice.proto

namespace GPBMetadata;

class FriendPushNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\FriendAddNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb010a16467269656e64507573684e6f746963652e70726f746f12174a" .
            "75626f2e4a754c69616f2e494d2e57782e50726f746f229f010a17467269" .
            "656e64507573684e6f746963654d65737361676512100a08576543686174" .
            "496418012001280912370a07467269656e647318022003280b32262e4a75" .
            "626f2e4a754c69616f2e494d2e57782e50726f746f2e467269656e644d65" .
            "7373616765120c0a0453697a65180320012805120d0a05436f756e741804" .
            "20012805120c0a0450616765180520012805120e0a065461736b49641806" .
            "20012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

