<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendDetectResultNotice.proto

namespace GPBMetadata;

class FriendDetectResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3020a1e467269656e64446574656374526573756c744e6f746963652e" .
            "70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f" .
            "22ff010a1f467269656e64446574656374526573756c744e6f746963654d" .
            "65737361676512100a085765436861744964180120012809120e0a065461" .
            "736b496418022001280312110a09537461727454696d6518032001280312" .
            "0f0a07456e6454696d6518042001280312120a0a497346696e6973686564" .
            "180520012808120d0a05436f756e7418062001280512110a09536b697043" .
            "6f756e7418072001280512100a0844656c436f756e74180820012805120f" .
            "0a075a6f6d6269657318092003280912130a0b426c6f636b65644c697374" .
            "180a2003280912120a0a42616e6e65644c697374180b2003280912140a0c" .
            "43616e63656c65644c697374180c20032809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

