<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendChangeNotice.proto

namespace GPBMetadata;

class FriendChangeNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\FriendAddNotice::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a18467269656e644368616e67654e6f746963652e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f22650a194672" .
            "69656e644368616e67654e6f746963654d65737361676512100a08576543" .
            "686174496418012001280912360a06467269656e6418032001280b32262e" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e467269656e64" .
            "4d657373616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

