<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendAddReqeustNotice.proto

namespace GPBMetadata;

class FriendAddReqeustNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4020a1c467269656e64416464526571657573744e6f746963652e7072" .
            "6f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f2282" .
            "020a1d467269656e64416464526571657573744e6f746963654d65737361" .
            "676512100a08576543686174496418012001280912100a08467269656e64" .
            "496418022001280912100a08467269656e644e6f18032001280912120a0a" .
            "467269656e644e69636b180420012809120e0a06526561736f6e18052001" .
            "2809120e0a06417661746172180620012809120e0a06536f757263651807" .
            "2001280512120a0a536f757263655573657218082001280912330a064765" .
            "6e64657218092001280e32232e4a75626f2e4a754c69616f2e494d2e5778" .
            "2e50726f746f2e456e756d47656e64657212100a0850726f76696e636518" .
            "0a20012809120c0a0443697479180b20012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

