<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetGroupSendHistoryTask.proto

namespace GPBMetadata;

class GetGroupSendHistoryTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95010a1d47657447726f757053656e64486973746f72795461736b2e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22" .
            "530a1e47657447726f757053656e64486973746f72795461736b4d657373" .
            "61676512100a085765436861744964180120012809120f0a07456e645469" .
            "6d65180220012803120e0a065461736b4964180520012803620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

