<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPoiListTask.proto

namespace GPBMetadata;

class GetPoiListTask
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d010a14476574506f694c6973745461736b2e70726f746f12174a7562" .
            "6f2e4a754c69616f2e494d2e57782e50726f746f22640a15476574506f69" .
            "4c6973745461736b4d65737361676512100a085765436861744964180120" .
            "012809120b0a034c6174180220012801120b0a034c6e6718032001280112" .
            "0f0a074b6579776f7264180420012809120e0a065461736b496418052001" .
            "2803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}
