<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSendHistoryPushNotice.proto

namespace GPBMetadata;

class GroupSendHistoryPushNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7020a2047726f757053656e64486973746f7279507573684e6f746963" .
            "652e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f" .
            "746f22a2010a0b4d6173734d657373616765120e0a06546f4c6973741801" .
            "20012809120f0a07546f436f756e74180220012805123d0a0b436f6e7465" .
            "6e745479706518032001280e32282e4a75626f2e4a754c69616f2e494d2e" .
            "57782e50726f746f2e456e756d436f6e74656e7454797065120f0a07436f" .
            "6e74656e7418042001280912120a0a43726561746554696d651805200128" .
            "03120e0a06537461747573180620012805227d0a2147726f757053656e64" .
            "486973746f7279507573684e6f746963654d65737361676512100a085765" .
            "43686174496418012001280912360a084d6573736167657318022003280b" .
            "32242e4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e4d6173" .
            "734d657373616765120e0a065461736b4964180320012803620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

