<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModifyFriendMemoTask.proto

namespace GPBMetadata;

class ModifyFriendMemoTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd010a1a4d6f64696679467269656e644d656d6f5461736b2e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f228d010a" .
            "1b4d6f64696679467269656e644d656d6f5461736b4d6573736167651210" .
            "0a08576543686174496418012001280912100a08467269656e6449641802" .
            "20012809120c0a044d656d6f180320012809120e0a065461736b49641804" .
            "20012803120c0a0444657363180520012809120d0a0550686f6e65180620" .
            "012809120f0a0744656c466c6167180720012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

