<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDelNotice.proto

namespace GPBMetadata;

class MsgDelNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a124d736744656c4e6f746963652e70726f746f12174a75626f2e" .
            "4a754c69616f2e494d2e57782e50726f746f22ba010a134d736744656c4e" .
            "6f746963654d65737361676512100a085765436861744964180120012809" .
            "12100a08467269656e644964180320012809120e0a06497353656e641804" .
            "20012808123d0a0b436f6e74656e745479706518052001280e32282e4a75" .
            "626f2e4a754c69616f2e494d2e57782e50726f746f2e456e756d436f6e74" .
            "656e7454797065120f0a07436f6e74656e7418062001280c120d0a054d73" .
            "67496418072001280312100a086d73675376724964180820012803620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

