<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhoneStateTaskResultNotice.proto

namespace GPBMetadata;

class PhoneStateTaskResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0010a2050686f6e6553746174655461736b526573756c744e6f746963" .
            "652e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f" .
            "746f22aa010a2150686f6e6553746174655461736b526573756c744e6f74" .
            "6963654d65737361676512100a085765436861744964180120012809120c" .
            "0a04496d656918022001280912140a0c426174746572794c6576656c1803" .
            "2001280512150a0d4368617267696e675374617465180420012805120f0a" .
            "074e65745479706518052001280912120a0a536463617264467265651806" .
            "2001280312130a0b536463617264546f74616c180720012803620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

