<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostMessageReadNotice.proto

namespace GPBMetadata;

class PostMessageReadNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82010a1b506f73744d657373616765526561644e6f746963652e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22420a" .
            "1c506f73744d657373616765526561644e6f746963654d65737361676512" .
            "100a08576543686174496418012001280912100a08467269656e64496418" .
            "0220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

