<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostFriendDetectCountNotice.proto

namespace GPBMetadata;

class PostFriendDetectCountNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6010a21506f7374467269656e64446574656374436f756e744e6f7469" .
            "63652e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e5072" .
            "6f746f229f010a22506f7374467269656e64446574656374436f756e744e" .
            "6f746963654d657373616765120e0a065461736b4964180120012803120d" .
            "0a05436f756e7418022001280512100a0844656c436f756e741803200128" .
            "0512120a0a497346696e697368656418042001280812110a09536b697043" .
            "6f756e74180520012805120f0a075a6f6d6269657318062003280912100a" .
            "085765436861744964180720012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

