<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostStopFriendDetectTask.proto

namespace GPBMetadata;

class PostStopFriendDetectTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a86010a1e506f737453746f70467269656e644465746563745461736b2e" .
            "70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f" .
            "22430a1f506f737453746f70467269656e644465746563745461736b4d65" .
            "737361676512100a085765436861744964180120012809120e0a06546173" .
            "6b4964180220012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

