<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostDeleteDeviceNotice.proto

namespace GPBMetadata;

class PostDeleteDeviceNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a1c506f737444656c6574654465766963654e6f746963652e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f222d0a" .
            "1d506f737444656c6574654465766963654e6f746963654d657373616765" .
            "120c0a04494d4549180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

