<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullCircleDetailTask.proto

namespace GPBMetadata;

class PullCircleDetailTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a1a50756c6c436972636c6544657461696c5461736b2e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22540a1b" .
            "50756c6c436972636c6544657461696c5461736b4d65737361676512100a" .
            "08576543686174496418012001280912100a08436972636c654964180320" .
            "01280312110a094765744269674d6170180420012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

