<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullSmsTask.proto

namespace GPBMetadata;

class PullSmsTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a1150756c6c536d735461736b2e70726f746f12174a75626f2e4a" .
            "754c69616f2e494d2e57782e50726f746f22680a1250756c6c536d735461" .
            "736b4d65737361676512100a085765436861744964180120012809120c0a" .
            "04494d454918022001280912110a09537461727454696d65180320012803" .
            "120f0a07456e6454696d65180420012803120e0a065461736b4964180520" .
            "012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

