<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullChatRoomQrCodeTaskResultNotice.proto

namespace GPBMetadata;

class PullChatRoomQrCodeTaskResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a2850756c6c43686174526f6f6d5172436f64655461736b526573" .
            "756c744e6f746963652e70726f746f12174a75626f2e4a754c69616f2e49" .
            "4d2e57782e50726f746f2295010a2950756c6c43686174526f6f6d517243" .
            "6f64655461736b526573756c744e6f746963654d657373616765120f0a07" .
            "5375636365737318012001280812120a0a43686174526f6f6d4964180220" .
            "01280912110a095172436f646555726c180320012809120e0a065461736b" .
            "496418042001280312100a085765436861744964180520012809120e0a06" .
            "4572724d7367180620012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

