<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullCallLogTask.proto

namespace GPBMetadata;

class PullCallLogTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a1550756c6c43616c6c4c6f675461736b2e70726f746f12174a75" .
            "626f2e4a754c69616f2e494d2e57782e50726f746f226c0a1650756c6c43" .
            "616c6c4c6f675461736b4d65737361676512100a08576543686174496418" .
            "0120012809120c0a04494d454918022001280912110a0953746172745469" .
            "6d65180320012803120f0a07456e6454696d65180420012803120e0a0654" .
            "61736b4964180520012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

