<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullEmojiInfoTask.proto

namespace GPBMetadata;

class PullEmojiInfoTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85010a1750756c6c456d6f6a69496e666f5461736b2e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f22490a1850756c" .
            "6c456d6f6a69496e666f5461736b4d65737361676512100a085765436861" .
            "744964180120012809120b0a034d6435180220012809120e0a065461736b" .
            "4964180320012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

