<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryHbStatusTaskResultNotice.proto

namespace GPBMetadata;

class QueryHbStatusTaskResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a23517565727948625374617475735461736b526573756c744e6f" .
            "746963652e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e" .
            "50726f746f22b0010a24517565727948625374617475735461736b526573" .
            "756c744e6f746963654d65737361676512100a0857654368617449641801" .
            "20012809120f0a0753756363657373180220012808120e0a064572724d73" .
            "67180320012809120d0a05486255726c180420012809120e0a0648625479" .
            "706518052001280512100a08486253746174757318062001280512110a09" .
            "52657653746174757318072001280512110a095374617475734d73671808" .
            "20012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

