<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RedirectNotice.proto

namespace GPBMetadata;

class RedirectNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98010a1452656469726563744e6f746963652e70726f746f12174a7562" .
            "6f2e4a754c69616f2e494d2e57782e50726f746f225f0a15526564697265" .
            "63744e6f746963654d657373616765120c0a045479706518012001280512" .
            "110a0953657276657255726c18022001280912120a0a536572766572506f" .
            "727418032001280512110a0955706c6f616455726c180420012809620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

