<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestTalkContentTaskResultNotice.proto

namespace GPBMetadata;

class RequestTalkContentTaskResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a285265717565737454616c6b436f6e74656e745461736b526573" .
            "756c744e6f746963652e70726f746f12174a75626f2e4a754c69616f2e49" .
            "4d2e57782e50726f746f22710a295265717565737454616c6b436f6e7465" .
            "6e745461736b526573756c744e6f746963654d65737361676512100a0857" .
            "6543686174496418012001280912100a084d736753767249641802200128" .
            "03120f0a074d736754797065180320012805120f0a07436f6e74656e7418" .
            "0420012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

