<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestChatRoomInfoTask.proto

namespace GPBMetadata;

class RequestChatRoomInfoTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a96010a1d5265717565737443686174526f6f6d496e666f5461736b2e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22" .
            "540a1e5265717565737443686174526f6f6d496e666f5461736b4d657373" .
            "61676512100a08576543686174496418012001280912120a0a4368617452" .
            "6f6f6d4964180220012809120c0a04466c6167180320012805620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

