<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SearchBizContactTask.proto

namespace GPBMetadata;

class SearchBizContactTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d010a1a53656172636842697a436f6e746163745461736b2e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f225e0a1b" .
            "53656172636842697a436f6e746163745461736b4d65737361676512100a" .
            "085765436861744964180120012809120f0a074b6579576f726418022001" .
            "2809120c0a0454797065180320012805120e0a065461736b496418042001" .
            "2803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

