<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendLuckyMoneyTask.proto

namespace GPBMetadata;

class SendLuckyMoneyTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca010a1853656e644c75636b794d6f6e65795461736b2e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f228c010a1953" .
            "656e644c75636b794d6f6e65795461736b4d65737361676512100a085765" .
            "43686174496418012001280912100a08467269656e644964180220012809" .
            "120d0a054d6f6e6579180320012805120e0a064e756d6265721804200128" .
            "05120e0a06506173737764180520012809120c0a04576973681806200128" .
            "09120e0a065461736b4964180720012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

