<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendMultiPictureTask.proto

namespace GPBMetadata;

class SendMultiPictureTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a1a53656e644d756c7469506963747572655461736b2e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f225f0a1b" .
            "53656e644d756c7469506963747572655461736b4d65737361676512100a" .
            "08576543686174496418012001280912100a08467269656e644964180220" .
            "012809120c0a0450696373180320032809120e0a065461736b4964180420" .
            "012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

