<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmsSentNotice.proto

namespace GPBMetadata;

class SmsSentNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b010a13536d7353656e744e6f746963652e70726f746f12174a75626f" .
            "2e4a754c69616f2e494d2e57782e50726f746f22530a14536d7353656e74" .
            "4e6f746963654d65737361676512100a0857654368617449641801200128" .
            "09120c0a04494d4549180220012809120d0a05536d734964180320012805" .
            "120c0a0454797065180420012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

