<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SphGetMentionTask.proto

namespace GPBMetadata;

class SphGetMentionTask
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a175370684765744d656e74696f6e5461736b2e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f227d0a18537068" .
            "4765744d656e74696f6e5461736b4d65737361676512100a085765436861" .
            "74496418012001280912120a0a4c6173744c696b65496418022001280312" .
            "150a0d4c617374436f6d6d656e74496418032001280312140a0c4c617374" .
            "466f6c6c6f774964180420012803120e0a065461736b4964180520012803" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}
