<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SphPostTask.proto

namespace GPBMetadata;

class SphPostTask
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9020a11537068506f73745461736b2e70726f746f12174a75626f" .
            "2e4a754c69616f2e494d2e57782e50726f746f22a2020a1253706850" .
            "6f73745461736b4d65737361676512100a0857654368617449641801" .
            "20012809120f0a07436f6e74656e7418022001280912110a094d6564" .
            "696154797065180320012805120e0a064d6564696173180420032809" .
            "120d0a05436f76657218052001280912430a03506f6918082001280b" .
            "32362e4a75626f2e4a754c69616f2e494d2e57782e50726f746f2e53" .
            "7068506f73745461736b4d6573736167652e506f694d657373616765" .
            "120e0a065461736b4964180a200128031a620a0a506f694d65737361" .
            "6765120c0a0443697479180120012809120c0a044e616d6518022001" .
            "2809120f0a0741646472657373180320012809120b0a034c61741804" .
            "20012802120b0a034c6e67180520012802120d0a05506f6949641806" .
            "20012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}
