<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeLuckyMoneyTask.proto

namespace GPBMetadata;

class TakeLuckyMoneyTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a1854616b654c75636b794d6f6e65795461736b2e70726f746f12" .
            "174a75626f2e4a754c69616f2e494d2e57782e50726f746f22710a195461" .
            "6b654c75636b794d6f6e65795461736b4d65737361676512100a08576543" .
            "686174496418012001280912100a08467269656e64496418022001280912" .
            "100a084d73675376724964180320012803120e0a064d73674b6579180420" .
            "012809120e0a065461736b4964180520012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

