<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeMoneyTaskResultNotice.proto

namespace GPBMetadata;

class TakeMoneyTaskResultNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2020a1f54616b654d6f6e65795461736b526573756c744e6f74696365" .
            "2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f22ed010a2054616b654d6f6e65795461736b526573756c744e6f746963" .
            "654d657373616765120f0a075375636365737318012001280812340a0443" .
            "6f646518022001280e32262e4a75626f2e4a754c69616f2e494d2e57782e" .
            "50726f746f2e456e756d4572726f72436f6465120e0a064572724d736718" .
            "0320012809120e0a065461736b4964180420012803120e0a064d73674b65" .
            "79180520012809120e0a06416d6f756e7418062001280512100a08576543" .
            "6861744964180720012809120e0a0653656e646572180820012809120c0a" .
            "045479706518092001280512120a0a53656e6465724e616d65180a200128" .
            "09620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

