<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerHistoryMsgPushTask.proto

namespace GPBMetadata;

class TriggerHistoryMsgPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a1f54726967676572486973746f72794d7367507573685461736b" .
            "2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f2297010a2054726967676572486973746f72794d736750757368546173" .
            "6b4d65737361676512100a08576543686174496418012001280912100a08" .
            "467269656e64496418022001280912110a09537461727454696d65180320" .
            "012803120f0a07456e6454696d65180420012803120c0a04466c61671805" .
            "20012805120d0a05436f756e74180620012805120e0a065461736b496418" .
            "0720012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

