<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerCircleMsgPushTask.proto

namespace GPBMetadata;

class TriggerCircleMsgPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a1e54726967676572436972636c654d7367507573685461736b2e" .
            "70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f" .
            "22680a1f54726967676572436972636c654d7367507573685461736b4d65" .
            "737361676512100a08576543686174496418012001280912130a0b4f6e6c" .
            "79436f6d6d656e74180220012808120e0a06476574416c6c180320012808" .
            "120e0a065461736b4964180420012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

