<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerChatMsgIdsPushTask.proto

namespace GPBMetadata;

class TriggerChatMsgIdsPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a1f54726967676572436861744d7367496473507573685461736b" .
            "2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f22580a2054726967676572436861744d7367496473507573685461736b" .
            "4d65737361676512100a08576543686174496418012001280912110a0953" .
            "7461727454696d65180320012803120f0a07456e6454696d651804200128" .
            "03620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

