<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerBizContactPushTask.proto

namespace GPBMetadata;

class TriggerBizContactPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88010a1f5472696767657242697a436f6e74616374507573685461736b" .
            "2e70726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f22440a205472696767657242697a436f6e74616374507573685461736b" .
            "4d65737361676512100a085765436861744964180120012809120e0a0654" .
            "61736b4964180220012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

