<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerChatRoomPushTask.proto

namespace GPBMetadata;

class TriggerChatRoomPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92010a1d5472696767657243686174526f6f6d507573685461736b2e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22" .
            "500a1e5472696767657243686174526f6f6d507573685461736b4d657373" .
            "61676512100a085765436861744964180120012809120c0a04466c616718" .
            "0220012805120e0a065461736b4964180320012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

