<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerQwConvPushTask.proto

namespace GPBMetadata;

class TriggerQwConvPushTask
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a1b547269676765725177436f6e76507573685461736b2e70" .
            "726f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f74" .
            "6f2283010a1c547269676765725177436f6e76507573685461736b4d" .
            "65737361676512100a08576543686174496418012001280912110a09" .
            "537461727454696d65180220012803120f0a07456e6454696d651803" .
            "20012803120e0a065461736b4964180520012803120d0a054c696d69" .
            "74180620012805120e0a064f6666736574180720012805620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}
