<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerUnreadPushTask.proto

namespace GPBMetadata;

class TriggerUnreadPushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a1b54726967676572556e72656164507573685461736b2e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22400a" .
            "1c54726967676572556e72656164507573685461736b4d65737361676512" .
            "100a085765436861744964180120012809120e0a065461736b4964180220" .
            "012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

