<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TriggerCirclePushTask.proto

namespace GPBMetadata;

class TriggerCirclePushTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a96010a1b54726967676572436972636c65507573685461736b2e70726f" .
            "746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f22560a" .
            "1c54726967676572436972636c65507573685461736b4d65737361676512" .
            "100a08576543686174496418012001280912110a09537461727454696d65" .
            "18022001280312110a09436972636c65496473180320032803620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

