<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpgradeDeviceAppNotice.proto

namespace GPBMetadata;

class UpgradeDeviceAppNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad020a1c557067726164654465766963654170704e6f746963652e7072" .
            "6f746f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f2266" .
            "0a17446576696365417070557067726164654d65737361676512110a0956" .
            "65724e756d626572180120012805120f0a0756657273696f6e1802200128" .
            "0912130a0b5061636b6167654e616d6518032001280912120a0a5061636b" .
            "61676555726c1804200128092283010a1d55706772616465446576696365" .
            "4170704e6f746963654d65737361676512100a0857654368617449641801" .
            "20012809120c0a04494d454918022001280912420a08417070496e666f73" .
            "18032003280b32302e4a75626f2e4a754c69616f2e494d2e57782e50726f" .
            "746f2e446576696365417070557067726164654d65737361676562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

