<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatLocationTask.proto

namespace GPBMetadata;

class WeChatLocationTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a185765436861744c6f636174696f6e5461736b2e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f222d0a19576543" .
            "6861744c6f636174696f6e5461736b4d65737361676512100a0857654368" .
            "61744964180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

