<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatLoginNotice.proto

namespace GPBMetadata;

class WeChatLoginNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TransportMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb020a175765436861744c6f67696e4e6f746963652e70726f746f1217" .
            "4a75626f2e4a754c69616f2e494d2e57782e50726f746f228e020a185765" .
            "436861744c6f67696e4e6f746963654d65737361676512120a0a53757070" .
            "6c6965724964180120012803120f0a07556e696f6e496418022001280312" .
            "3d0a0b4163636f756e745479706518032001280e32282e4a75626f2e4a75" .
            "4c69616f2e494d2e57782e50726f746f2e456e756d4163636f756e745479" .
            "706512550a075765436861747318042003280b32442e4a75626f2e4a754c" .
            "69616f2e494d2e57782e50726f746f2e5765436861744c6f67696e4e6f74" .
            "6963654d6573736167652e5765436861744c6f67696e4d6573736167651a" .
            "370a125765436861744c6f67696e4d65737361676512100a085765436861" .
            "744964180120012809120f0a0749734c6f67696e18022001280862067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

