<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatLoginNoticeResp.proto

namespace GPBMetadata;

class WeChatLoginNoticeResp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6f0a1b5765436861744c6f67696e4e6f74696365526573702e70726f74" .
            "6f12174a75626f2e4a754c69616f2e494d2e57782e50726f746f222f0a1c" .
            "5765436861744c6f67696e4e6f74696365526573704d657373616765120f" .
            "0a0757654368617473180120032809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

