<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatOfflineNotice.proto

namespace GPBMetadata;

class WeChatOfflineNotice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a195765436861744f66666c696e654e6f746963652e70726f746f" .
            "12174a75626f2e4a754c69616f2e494d2e57782e50726f746f224c0a1a57" .
            "65436861744f66666c696e654e6f746963654d65737361676512100a0857" .
            "65436861744964180120012809120c0a04494d4549180220012809120e0a" .
            "06526561736f6e180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

