<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WechatLogoutTask.proto

namespace GPBMetadata;

class WechatLogoutTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a660a165765636861744c6f676f75745461736b2e70726f746f12174a75" .
            "626f2e4a754c69616f2e494d2e57782e50726f746f222b0a175765636861" .
            "744c6f676f75745461736b4d65737361676512100a085765436861744964" .
            "180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

