<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CircleNewPublishNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage\CircleContentMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage.CircleContentMessage.CircleNewsContentMessage</code>
 */
class CircleNewsContentMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 缩略图
     *
     * Generated from protobuf field <code>string ThumbImg = 1;</code>
     */
    private $ThumbImg = '';
    /**
     * 链接地址 视频地址等
     *
     * Generated from protobuf field <code>string Url = 2;</code>
     */
    private $Url = '';
    /**
     * 标题等
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     */
    private $Description = '';
    /**
     * 媒体id
     *
     * Generated from protobuf field <code>string mediaId = 4;</code>
     */
    private $mediaId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ThumbImg
     *           缩略图
     *     @type string $Url
     *           链接地址 视频地址等
     *     @type string $Description
     *           标题等
     *     @type string $mediaId
     *           媒体id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CircleNewPublishNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 缩略图
     *
     * Generated from protobuf field <code>string ThumbImg = 1;</code>
     * @return string
     */
    public function getThumbImg()
    {
        return $this->ThumbImg;
    }

    /**
     * 缩略图
     *
     * Generated from protobuf field <code>string ThumbImg = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setThumbImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ThumbImg = $var;

        return $this;
    }

    /**
     * 链接地址 视频地址等
     *
     * Generated from protobuf field <code>string Url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->Url;
    }

    /**
     * 链接地址 视频地址等
     *
     * Generated from protobuf field <code>string Url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->Url = $var;

        return $this;
    }

    /**
     * 标题等
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * 标题等
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * 媒体id
     *
     * Generated from protobuf field <code>string mediaId = 4;</code>
     * @return string
     */
    public function getMediaId()
    {
        return $this->mediaId;
    }

    /**
     * 媒体id
     *
     * Generated from protobuf field <code>string mediaId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mediaId = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CircleNewsContentMessage::class, \Jubo\JuLiao\IM\Wx\Proto\CircleInformationMessage_CircleContentMessage_CircleNewsContentMessage::class);

