<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AcceptFriendAddRequestTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto\AcceptFriendAddRequestTaskMessage;

use UnexpectedValueException;

/**
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.AcceptFriendAddRequestTaskMessage.EnumFriendAddOperation</code>
 */
class EnumFriendAddOperation
{
    /**
     * 忽略消息
     *
     * Generated from protobuf enum <code>Ignore = 0;</code>
     */
    const Ignore = 0;
    /**
     * 接受
     *
     * Generated from protobuf enum <code>Accept = 1;</code>
     */
    const Accept = 1;
    /**
     * 拒绝
     *
     * Generated from protobuf enum <code>Reject = 2;</code>
     */
    const Reject = 2;

    private static $valueToName = [
        self::Ignore => 'Ignore',
        self::Accept => 'Accept',
        self::Reject => 'Reject',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EnumFriendAddOperation::class, \Jubo\JuLiao\IM\Wx\Proto\AcceptFriendAddRequestTaskMessage_EnumFriendAddOperation::class);

