<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostSNSNewsTask.proto

namespace Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage\AttachmentMessage;

use UnexpectedValueException;

/**
 *附件类型
 *
 * Protobuf type <code>Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.AttachmentMessage.EnumAttachType</code>
 */
class EnumAttachType
{
    /**
     *链接
     *
     * Generated from protobuf enum <code>Link = 0;</code>
     */
    const Link = 0;
    /**
     *图片
     *
     * Generated from protobuf enum <code>Picture = 2;</code>
     */
    const Picture = 2;
    /**
     *短视频
     *
     * Generated from protobuf enum <code>ShortVideo = 3;</code>
     */
    const ShortVideo = 3;
    /**
     *不支持， 与ShortVideo相同，不区分长短视频
     *
     * Generated from protobuf enum <code>LongVideo = 4;</code>
     */
    const LongVideo = 4;
    /**
     *视频号
     *
     * Generated from protobuf enum <code>ShiPinHao = 5;</code>
     */
    const ShiPinHao = 5;
    /**
     *所有链接（包括小程序等）
     *
     * Generated from protobuf enum <code>ExtLink = 6;</code>
     */
    const ExtLink = 6;
    /**
     *视频号直播
     *
     * Generated from protobuf enum <code>FinderLive = 7;</code>
     */
    const FinderLive = 7;

    private static $valueToName = [
        self::Link => 'Link',
        self::Picture => 'Picture',
        self::ShortVideo => 'ShortVideo',
        self::LongVideo => 'LongVideo',
        self::ShiPinHao => 'ShiPinHao',
        self::ExtLink => 'ExtLink',
        self::FinderLive => 'FinderLive',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EnumAttachType::class, \Jubo\JuLiao\IM\Wx\Proto\PostSNSNewsTaskMessage_AttachmentMessage_EnumAttachType::class);

