<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoomPushNotice.proto

namespace Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jubo.JuLiao.IM.Wx.Proto.ChatRoomMessage.DisplayNameMessage</code>
 */
class DisplayNameMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * 群成员
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     * 群显示名
     *
     * Generated from protobuf field <code>string ShowName = 2;</code>
     */
    private $ShowName = '';
    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Inviter = 3;</code>
     */
    private $Inviter = '';
    /**
     * &2048 群管理员，其他未知
     *
     * Generated from protobuf field <code>int32 Flag = 4;</code>
     */
    private $Flag = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserName
     *           群成员
     *     @type string $ShowName
     *           群显示名
     *     @type string $Inviter
     *           邀请者
     *     @type int $Flag
     *           &2048 群管理员，其他未知
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChatRoomPushNotice::initOnce();
        parent::__construct($data);
    }

    /**
     * 群成员
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * 群成员
     *
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * 群显示名
     *
     * Generated from protobuf field <code>string ShowName = 2;</code>
     * @return string
     */
    public function getShowName()
    {
        return $this->ShowName;
    }

    /**
     * 群显示名
     *
     * Generated from protobuf field <code>string ShowName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShowName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShowName = $var;

        return $this;
    }

    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Inviter = 3;</code>
     * @return string
     */
    public function getInviter()
    {
        return $this->Inviter;
    }

    /**
     * 邀请者
     *
     * Generated from protobuf field <code>string Inviter = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInviter($var)
    {
        GPBUtil::checkString($var, True);
        $this->Inviter = $var;

        return $this;
    }

    /**
     * &2048 群管理员，其他未知
     *
     * Generated from protobuf field <code>int32 Flag = 4;</code>
     * @return int
     */
    public function getFlag()
    {
        return $this->Flag;
    }

    /**
     * &2048 群管理员，其他未知
     *
     * Generated from protobuf field <code>int32 Flag = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->Flag = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DisplayNameMessage::class, \Jubo\JuLiao\IM\Wx\Proto\ChatRoomMessage_DisplayNameMessage::class);

